Added GitHub actions to validate issue number in PR bodies
HarshCasper/Rotten-Scripts pull request #1001
Opened 2021-04-19 21:42 UTC by XZANATOL

# Description

There was a need to automate PR body validation, check for valid issue numbers, and apply a corresponding decission if true or false. (This is the first action out of two)

The GitHub action can be viewed in action from [here](https://github.com/XZANATOL/Github-actions-test/pull/18)

Fixes #757 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2021-04-19 21:51 UTC, XZANATOL commented
`` PR has a valid Issue? / checker (pull_request) `` has failed because the action doesn't have access to the secret envs yet. (will have after merging)

2021-04-21 09:49 UTC, vybhav72954 requested changes

2021-04-21 09:49 UTC, vybhav72954 commented on .github/actions/PR_has_a_valid_issue/main.py
> +pattern = "#\d+"  # Used pattern to search for Issues.
In this Repo, we follow this style:

```
# Used pattern to search for Issues.
pattern = "#\d+"
```
Can you change accordingly?

2021-04-21 09:49 UTC, vybhav72954 commented on .github/workflows/Check if issue exists.yml
> +          gh pr edit $PRNUM --add-label "PR:Ready-to-Merge"
Change this label to `PR:Ready-to-Review`

2021-04-21 09:49 UTC, vybhav72954 commented on .github/actions/PR_has_a_valid_issue/main.py
> +
Only 1 blank line at the end please

2021-04-21 14:03 UTC, vybhav72954 commented
@XZANATOL I will do a one-final run from my side just to ensure everything is working. Will get this merge tomorrow.

I was just wondering, If the PR doesn't have the label, can you make it a draft PR as well, that functionality is a bit weird from GitHub's API, but pretty sure is possible. What do you think?

2021-04-21 14:20 UTC, XZANATOL commented
@vybhav72954 hmmm, the action will either assign a `` PR:Ready-to-Review `` or `` PR:No-Issue `` label .. all what is needed is the carteria under which the PR will get drafted :thinking: `` gh `` CLI does support this change so It won't be a problem

2021-04-21 14:23 UTC, vybhav72954 commented
> @vybhav72954 hmmm, the action will either assign a `` PR:Ready-to-Review `` or `` PR:No-Issue `` label .. all what is needed is the carteria under which the PR will get drafted :thinking: `` gh `` CLI does support this change so It won't be a problem

Yeah so what i want is, that if the PR has no issue, or basically a `PR:No-Issue` label.

Just run more job to make it a draft.

2021-04-21 14:25 UTC, XZANATOL commented
Easy one, but if the author changed the body and put a valid issue num.. shall the action revert the change?

2021-04-21 14:29 UTC, vybhav72954 commented
> Easy one, but if the author changed the body and put a valid issue num.. shall the action revert the change?

If that's possible, would be a great addition. If not, then modify the comment accordingly.

Something like this PR is drafted for now. After linking the issue properly make to ready for review.

Also as we have a completely separate label for properly edited PRs, i think marking it Ready won't be a problem?

2021-04-21 14:36 UTC, XZANATOL commented
Gonna test it out and update you ASAP, and I think it won't be a problem to mark the PR ready as any edits that doesn't relate to the issue number will be from the mentor's side (and mentors can add `` PR:Under-Review `` label to indicate that it is under review process)

2021-04-21 18:56 UTC, XZANATOL commented
@vybhav72954 I was looking for the right syntax of gh CLI command to mark a draft PR to ready and the opposite. What I've found is gh can convert a draft PR to ready-to-review but not the opposite. GitHub didn't support this yet - check [this](https://github.com/cli/cli/issues/740#issuecomment-630319524) -. I though about changing the metadata of the PR using `` gh api `` but it seems I can't edit the metadata using it. (also not supported)

2021-04-24 17:28 UTC, XZANATOL commented
@vybhav72954 updates?

2021-04-24 20:59 UTC, vybhav72954 commented
> @vybhav72954 updates?

Yup as i thought. @HarshCasper This looks gud to me

2021-04-24 20:59 UTC, vybhav72954 approved these changes

2021-04-25 21:41 UTC, vybhav72954 commented
@XZANATOL Am pretty sure you can add an image as well right? Just upload it on an image hosting portal and paste the link with the job-creating comment.

2021-04-25 21:43 UTC, vybhav72954 commented
![f](https://user-images.githubusercontent.com/49750343/116010549-4a9dbf00-a63d-11eb-9c58-1b86e3273089.PNG)
Can you make sure this image is a part of comment as well, and make sure to change the comment to something like, **It should look like this**

2021-04-25 22:15 UTC, XZANATOL commented
I think yea, gonna prepare this rught away

2021-04-26 11:47 UTC, vybhav72954 commented
I will get this merge tonight for sure.

2021-04-28 17:03 UTC, HarshCasper approved these changes

2021-04-28 17:03 UTC, merged