Updated README.md
HarshCasper/Rotten-Scripts pull request #1015
Opened 2021-04-22 14:31 UTC by ireneelizabethsabu

# Description
Fixes #1013 

## Type of change
- [ ] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2021-04-22 15:35 UTC, vybhav72954 requested changes

2021-04-22 15:35 UTC, vybhav72954 commented on JavaScript/README.md
> +- [List of those who starred and un-starred a repo](Stargazers)
Follow the alphabetical order here as well. (I  know stargazers is the name, but acc to description you have provided it shouldn't be here)

2021-04-23 04:56 UTC, ireneelizabethsabu commented
Sorted description in alphabetical order .Please review the PR @vybhav72954

2021-04-24 14:25 UTC, vybhav72954 requested changes

2021-04-24 14:25 UTC, vybhav72954 commented on JavaScript/README.md
> +- [Bulk LinkedIn Requests sending](Bulk_LinkedIn_Requests)
Lets keep to `Sender`

2021-04-24 14:25 UTC, vybhav72954 commented on JavaScript/README.md
>  - [Download all Github repositories](Download_All_Repos)
Lets keep to `Repositories`

2021-04-24 14:25 UTC, vybhav72954 commented on JavaScript/README.md
> +- [Github Good First Issues extractor](Github_Good_First_Issues)
`Github Good First Issues Extractor`

2021-04-24 14:25 UTC, vybhav72954 commented on JavaScript/README.md
> +- [List of those who starred and un-starred a repo](Stargazers)
`GitHub Stargrazers`

2021-04-24 14:25 UTC, vybhav72954 commented on JavaScript/README.md
> +- [Twitter Common Followers for two users](Twitter_Followers_Overlap)
`Twitter Mutual Followers`

2021-04-24 14:25 UTC, vybhav72954 commented on JavaScript/README.md
>  - [Follow automatically on Instagram](Follow_Instagram)
`Instagram Follow Bot`

2021-04-24 14:25 UTC, vybhav72954 commented on JavaScript/README.md
>  - [Like Posts automatically on Instagram](Instagram_Like)
`Instagram Like Bot`

2021-04-24 16:50 UTC, ireneelizabethsabu commented
Please review the PR @vybhav72954

2021-04-28 18:11 UTC, vybhav72954 approved these changes

2021-04-28 18:12 UTC, merged