Password Vulnerability Checker
HarshCasper/Rotten-Scripts pull request #1024
Opened 2021-04-23 21:22 UTC by RohiniRG

# Description

The python script checks if a password has been exposed to a data breach and the number of time it has occured, thus proving the password to be vulnerable for further attacks.

Fixes #993 

## Type of change

_Please delete options that are not relevant._

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2021-04-24 09:57 UTC, RohiniRG commented
@vybhav72954 could you please have a look

2021-04-24 18:56 UTC, vybhav72954 requested changes

2021-04-24 18:56 UTC, vybhav72954 commented on Python/Pwned_Passwords/README.md
> +https://haveibeenpwned.com/API/v3
A hyperlink, please in place of a direct URL

2021-04-24 18:56 UTC, vybhav72954 commented on Python/Pwned_Passwords/README.md
> +- The python script uses haveibeenpwned.com API to check if your password has been exposed to data breaches and how many times it has been seen.
haveibeenpwned.com in backticks, similary. pwned in bold

2021-04-24 18:56 UTC, vybhav72954 commented on Python/Pwned_Passwords/README.md
> +# Password Vulnerability Checker
More like a test rather than a check?

2021-04-25 12:25 UTC, RohiniRG commented
@vybhav72954 I made changes to the README accordingly, please have a look

2021-04-25 21:34 UTC, vybhav72954 requested changes

2021-04-25 21:34 UTC, vybhav72954 commented on Python/Pwned_Passwords/README.md
> +- Paste the token (password) in a .env file (Take the .env.example as an example)
Revert these changes please. ```.env``` looked good.

2021-04-27 04:26 UTC, RohiniRG commented
@vybhav72954 I reverted the few changes in README

2021-05-06 05:59 UTC, RohiniRG commented
@vybhav72954 @HarshCasper could you please have a look

2021-05-12 14:25 UTC, vybhav72954 approved these changes
Thank you for a well structured PR

2021-05-12 14:26 UTC, merged