Added Base-N Calculator files
HarshCasper/Rotten-Scripts pull request #1046
Opened 2021-05-03 03:40 UTC by XZANATOL

# Description

Added Base-N calculator files.

Fixes #1044 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2021-05-03 03:46 UTC, XZANATOL commented
@vybhav72954 Hi there, :D
I'm going to DM you this night (It's 6:00 AM in my timezone rn) about something considering the recently added GitHub Action. Can you take some time in reviewing this one for the mean time?

2021-05-17 07:09 UTC, vybhav72954 requested changes
Hey @XZANATOL Sorry for delay, everything looks good, just 1 major change: Missing docstrings for every function

2021-05-17 07:09 UTC, vybhav72954 commented on Python/Base-N-Calc/Readme.md
> +The project was built as a contribution during [GSSOC'21](https://gssoc.girlscript.tech/).
Remove l31 please

2021-05-17 07:09 UTC, vybhav72954 commented on Python/Base-N-Calc/script.py
> +    # Converting the integeral part
We need docstrings not comments

2021-06-02 12:00 UTC, sohamsshah commented
Are you working on this @XZANATOL ?

2021-07-04 23:41 UTC, closed without merging