Reddit Scraper added
HarshCasper/Rotten-Scripts pull request #1063
Opened 2021-05-15 12:18 UTC by RohiniRG

# Description

A Reddit scraper which scrapes the post of a particular subreddit to obtain information of author, upvotes, content, and so on and stores in the desired `.csv` file

Fixes #1045

## Type of change

_Please delete options that are not relevant._

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update
- [X] Documentation Update

# Checklist:

- [X] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2021-05-17 17:49 UTC, vybhav72954 approved these changes

2021-05-19 14:54 UTC, vybhav72954 requested changes
The script on the first glace looks good. Please update the Python README as well with the path of the script. Commit that file and I will merge

2021-05-19 18:03 UTC, RohiniRG commented
@vybhav72954 Have a look

2021-05-31 18:56 UTC, HarshCasper approved these changes

2021-05-31 18:56 UTC, merged