add the folder Blood Alcohol Content
HarshCasper/Rotten-Scripts pull request #1066
Opened 2021-05-18 04:36 UTC by soumik2012

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2021-05-18 04:40 UTC, soumik2012 commented
@vybhav72954 please check my PR

2021-05-19 14:52 UTC, vybhav72954 requested changes

2021-05-19 14:52 UTC, vybhav72954 commented on Python/Blood Alcohol Content/Blood_Alcohol_Content.py
> +class BAC(object):
We need docstrings, Class Docstrings and `__inti__` is not mandatory, but for the rest of the methods, docstrings are a must. Update accordingly.

2021-05-19 14:52 UTC, vybhav72954 commented on Python/Blood Alcohol Content/Blood_Alcohol_Content.py
> +    #BAC formula for man
Nitpicking here but `# BAC formula for man`

Change man to males as well.
Update at other places accordingly.

2021-05-19 14:52 UTC, vybhav72954 commented on Python/Blood Alcohol Content/README.md
> +Want to know how much amount of alcohol you drank? Well, the Blood alcohol content program will help you find out the alcohol intake.
It would be a great idea to elaborate on the concept of BAC here as well. Not everyone understands the origin of the formula. PLease add more details

2021-05-22 15:27 UTC, HarshCasper requested changes
I don't know who might need this, but as far as **I understand** no one would exactly rely on a script to find the alcohol content in their blood. It might have a better use-case through a Mobile App or something more accessible, but I don't think that a person would go over a terminal to find the alcohol present in their blood, after a heavy drink. 

Unfortunately, I don't find any utility for this script.

2021-05-22 15:27 UTC, closed without merging