jupyter notebook convertr for .ipynb files to pdf,html,python,markdow…
HarshCasper/Rotten-Scripts pull request #1094
Opened 2021-06-01 07:38 UTC by venkateshpensalwar

# Description

jupyter notebook converter to convert .ipynb files to pdf, markdown, HTML, python files.

Fixes #1093 

## Type of change

- [ ✔️ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ✔️ ] My code follows the style guidelines(Clean Code) of this project
- [✔️  ] I have performed a self-review of my own code
- [✔️  ] I have commented my code, particularly in hard-to-understand areas
- [✔️  ] I have created a helpful and easy to understand `README.md`
- [✔️  ] My changes generate no new warnings
- [✔️  ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2021-06-01 07:59 UTC, venkateshpensalwar commented
@vybhav72954  can you tell me how i can remove errors from this PR checking i am new to this thing

2021-06-21 17:28 UTC, iamakkkhil commented
create a function for your file conversion and use main function to drive the code

2021-06-21 17:31 UTC, iamakkkhil commented
create a requirements.txt file

2021-07-08 00:30 UTC, vybhav72954 commented on Python/Jupyter_Notebook_Convertor/notebook_convertor.py
> +"""This Program helps user to convert jupyter notebook to HTML,MarkDown,PDF,python file"""
We don't need a script docstring.

2021-07-08 01:51 UTC, venkateshpensalwar commented
Ok I will remove

On Thu, 8 Jul 2021, 6:00 am vybhav72954, ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In Python/Jupyter_Notebook_Convertor/notebook_convertor.py
> <https://github.com/HarshCasper/Rotten-Scripts/pull/1094#discussion_r665788688>
> :
>
> > @@ -0,0 +1,38 @@
> +"""This Program helps user to convert jupyter notebook to HTML,MarkDown,PDF,python file"""
>
> We don't need a script docstring.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HarshCasper/Rotten-Scripts/pull/1094#pullrequestreview-701546170>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AK52CJHAVOL5BXLQFFQXPA3TWTWS5ANCNFSM454CTU4Q>
> .
>

2021-07-08 13:41 UTC, venkateshpensalwar commented
i removed @vybhav72954 Docstring

2021-07-11 05:47 UTC, iamakkkhil requested changes

2021-07-11 05:47 UTC, iamakkkhil commented on Python/Jupyter_Notebook_Convertor/notebook_convertor.py
> +
remove these lines, and I already requested some changes

2021-07-11 05:50 UTC, venkateshpensalwar commented
Yes I will do my health is not well give me some days

2021-07-11 05:50 UTC, venkateshpensalwar commented
Yes I will do my health is not well give me some days

2021-10-03 08:40 UTC, HarshCasper commented
Closing the PR because of no updates.

2021-10-03 08:40 UTC, closed without merging