Linkedin Wish Sender
HarshCasper/Rotten-Scripts pull request #1124
Opened 2021-06-17 16:47 UTC by Sukriti-sood

# Description

Added Script that Sends the Wishes by Message to the first Connections on Linkedin on their Birthdays or any Other Good News Like Start New Position, Work Anniversary etc.

Fixes #1020 

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2021-06-21 06:31 UTC, HarshCasper requested changes

2021-06-21 06:31 UTC, HarshCasper commented on Python/Linkedin_Wishes_Sender/credentials.json
> +}
Add a new line at the EOF

2021-06-21 06:31 UTC, HarshCasper commented on Python/Linkedin_Wishes_Sender/Readme.md
> +- Chrome
Redundant requirements; Everyone using the Script should have these

2021-06-21 06:31 UTC, HarshCasper commented on Python/Linkedin_Wishes_Sender/Readme.md
> +- Install bs4 (```pip3 install bs4```)
Put a `requirements.txt` and put all of the dependencies there

2021-06-21 06:31 UTC, HarshCasper commented on Python/Linkedin_Wishes_Sender/Readme.md
> +
Can you add a GIF showing the script in action if possible?

2021-06-21 06:31 UTC, HarshCasper commented on Python/Linkedin_Wishes_Sender/Readme.md
> +
Remove extra lines here

2021-06-21 06:31 UTC, HarshCasper commented on Python/Linkedin_Wishes_Sender/script.py
> +    main()
Add a new line at the EOF

2021-06-21 06:31 UTC, HarshCasper commented on Python/Linkedin_Wishes_Sender/script.py
> +
Remove extra lines of code wherever possible

2021-06-21 06:31 UTC, HarshCasper commented on Python/Linkedin_Wishes_Sender/script.py
> +
Remove extra lines of code wherever possible

2021-06-21 06:32 UTC, HarshCasper commented
@Sukriti-sood Are you participating in some OSS program apart from PSoC '21 ?

2021-06-23 11:08 UTC, Sukriti-sood commented
> @Sukriti-sood Are you participating in some OSS program apart from PSoC '21 ?

yes ,LGM-SOC

2021-07-12 04:27 UTC, HarshCasper approved these changes

2021-07-12 04:27 UTC, merged