Translator and Language Detector Tool using Python 3
HarshCasper/Rotten-Scripts pull request #1130
Opened 2021-06-18 16:37 UTC by abhisheks008

# Description

This python script is to build a translator tool through which we can translate from one language to another, it can be applicable for a word, a sentence or a paragraph. Also this tool will detect the input language as well

Fixes #1128 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Checklist:
- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2021-06-19 05:08 UTC, abhisheks008 commented
@HarshCasper Please take a look at this. I have informed this issue in the discord channel as well, why this is not being verified despite of the files are perfectly running and created successfully.

2021-06-19 05:08 UTC, abhisheks008 commented
- [x] LGMSOC Participant

2021-06-20 14:24 UTC, abhisheks008 commented
@HarshCasper Please check the PR

2021-06-21 06:23 UTC, HarshCasper requested changes
The Code Quality is quite poor. Remove the Jupyter Notebook, sanitize the script and maybe then I would be able to review it.

2021-06-21 06:31 UTC, abhisheks008 commented
@HarshCasper updated the required changes.

2021-07-08 00:20 UTC, vybhav72954 commented on Python/Translator_and_Language_Detector/Language Detection and Translation.py
> +# translate a Indonesia text to english text (by default)
Interesting, your profile seems Indian,  am I supposed to believe that Indonesian is your first language that's why you have made it default?

2021-07-08 00:23 UTC, vybhav72954 commented
Oh never mind, code plagiarised from [here](https://www.kaggle.com/khotijahs1/how-to-translate-and-detect-language-in-python).

Look I am open to code reuse (and trust me I am very lenient with it), but this is simply copy-pasting someone else's work. WOuld love to see some other contribution from you. Thanks

2021-07-08 00:23 UTC, closed without merging