MAD_LIBS DISCORD BOT #1142
HarshCasper/Rotten-Scripts pull request #1153
Opened 2021-06-24 13:10 UTC by DhirajChauhan40

# Description

This is a discord bot that takes inputs from the user and gives you funny phrases which will make your day with a timeout, always-on features.
@HarshCasper Please check and update, Thanks for the opportunity.
Fixes #1142 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2021-06-24 13:11 UTC, DhirajChauhan40 commented
@HarshCasper Can you please put LGMSOC'21 label under this project

2021-06-25 17:58 UTC, RohiniRG requested changes
Good work!
Just add more comments to your code and make the requested changes.

2021-06-25 17:58 UTC, RohiniRG commented on Python/MAD_LIBS_BOT/keep_alive.py
> +    t.start()
Add a newline at the end of the file.

2021-06-25 17:58 UTC, RohiniRG commented on Python/MAD_LIBS_BOT/main.py
> +bot.run('TOKEN') #replace this token with yours
Create a `.env` file to store the tokens. You can refer from [here](https://github.com/HarshCasper/Rotten-Scripts/blob/master/Python/Network_passwords/.env.example).

2021-06-25 17:58 UTC, RohiniRG commented on Python/MAD_LIBS_BOT/main.py
> +bot.run('TOKEN') #replace this token with yours
Add a newline at the end of the file

2021-06-25 17:58 UTC, RohiniRG commented on Python/MAD_LIBS_BOT/requirements.txt
> +discord.py
Create your `requirements.txt` as follows like [here](https://github.com/HarshCasper/Rotten-Scripts/blob/master/Python/Coderforces_Problem_Scrapper/requirements.txt). You can refer from [here](https://note.nkmk.me/en/python-pip-install-requirements/#:~:text=If%20you%20output%20pip%20freeze%20to%20a%20file%20with%20redirect%20%3E%2C%20you%20can%20use%20that%20file%20to%20install%20packages%20of%20the%20same%20version%20as%20the%20original%20environment%20in%20another%20environment)

2021-06-25 17:58 UTC, RohiniRG commented on Python/MAD_LIBS_BOT/readme.md
> +<img src="output.png">
Refer to this [link](https://github.com/HarshCasper/Rotten-Scripts/blob/master/CONTRIBUTING.md#note--do-not-add-images-rather-) and add links to the images.
Write it as `![Image](Imgur_link)]`

2021-06-25 17:58 UTC, RohiniRG commented on Python/MAD_LIBS_BOT/readme.md
> +# install the requirements
Call the `requirements.txt` file here. Refer [this](https://note.nkmk.me/en/python-pip-install-requirements/#:~:text=Copy%20or%20move%20this%20requirements.txt%20to%20another%20environment%20and%20install%20with%20it.).

2021-06-27 15:03 UTC, DhirajChauhan40 commented
@RohiniRG @HarshCasper I have done the requested changes, can you check now?

2021-06-28 09:17 UTC, RohiniRG requested changes

2021-06-28 09:17 UTC, RohiniRG commented on Python/MAD_LIBS_BOT/readme.md
> +$ pip install -r requirements.txt
Only keep this command: 
 ```python 
$ pip install -r requirements.txt 
```
This will do all the work, delete the others

2021-06-28 09:17 UTC, RohiniRG commented on Python/MAD_LIBS_BOT/readme.md
> +
Add a usage instruction

2021-06-28 09:17 UTC, RohiniRG commented on Python/MAD_LIBS_BOT/readme.md
> +
Modify the README according to the template README of this repo.

2021-06-28 09:17 UTC, RohiniRG commented on Python/MAD_LIBS_BOT/readme.md
> +````
Add a usage instruction

2021-06-28 09:17 UTC, RohiniRG commented on Python/MAD_LIBS_BOT/main.py
> +bot.run('TOKEN') #replace this token with yours
As mentioned in the previous review, create a `.env` file to store the tokens.

2021-06-29 12:14 UTC, HarshCasper requested changes
Good Work! 

But I'm sorry, I won't be able to merge the PR. The project simply states that we accept plain scripts that can be launched from Terminal for automating mundane tasks. 

However, we don't accept full-fledged apps, and in this case, we have a complete Flask App running a Discord bot. We would have adopted it for a different use case but it doesn't seem to satisfy our use-case anywhere. 

Let me know your thoughts about the same.

2021-07-11 05:45 UTC, RohiniRG commented
@DhirajChauhan40 there has been no discussion from your side, I'll have to close the PR.

2021-07-11 05:45 UTC, closed without merging