chore: formatted code using black (HarshCasper#1171)
HarshCasper/Rotten-Scripts pull request #1175
Opened 2021-07-08 12:20 UTC by kadatatlukishore

# Description
issue #1171 
Created a Script to fetch all the Pull Requests created by a User on a GitHub Organization and store it in a Markdown Table.

The script should take the username and the organization name as an argument and result in a markdown file with a table with the following content:

- Title of PR
- Link of PR
- Status (Merged/Closed)

# Checklist:
 My code follows the style guidelines(Clean Code) of this project
 I have performed a self-review of my own code
 I have commented my code, particularly in hard-to-understand areas
 I have created a helpful and easy to understand README.md
 I have made corresponding changes to the documentation
 My changes generate no new warnings
 I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2021-07-08 12:30 UTC, vybhav72954 requested changes
Everything looks good, although the README could be a bit better maybe? Take inspiration from some other REAMEs in the projects? ALthough it looks good right now as well, but in case you can add some more info or something, would be great.

2021-07-08 12:30 UTC, vybhav72954 commented on Python/Fetch_Contributions/README.md
> +## Example Markdown File:
You have already uploaded the md file, no need to repeat the same in the README> Just provide a link to the file here?

2021-07-08 12:30 UTC, vybhav72954 commented on Python/Fetch_Contributions/README.md
> +We will get the resuts in a file like **above** table.
Consider adding an author section as well?

2021-07-08 12:31 UTC, vybhav72954 commented
Also please use `#Fixes <issue number` in the PR body

2021-07-08 12:38 UTC, kadatatlukishore commented
Hey @vybhav72954  , I am a newbie. Can I create another pull request need to do some changes or Can I change in repository?

2021-07-08 13:06 UTC, vybhav72954 commented
> Hey @vybhav72954  , I am a newbie. Can I create another pull request need to do some changes or Can I change in repository?

Seems like you figured it out. Awesome

2021-07-08 13:07 UTC, kadatatlukishore commented
@vybhav72954 Thanks. Yes, required changes are made.

2021-07-09 14:32 UTC, kadatatlukishore commented
Hey @vybhav72954 , I made all the necessary changes. Only one security issue is there for `from lxml import html` line. I've used to parse html using xpath. So, most of the code has been written using it.

2021-07-09 17:40 UTC, HarshCasper commented
> Hey @vybhav72954 , I made all the necessary changes. Only one security issue is there for `from lxml import html` line. I've used to parse html using xpath. So, most of the code has been written using it.

Don't worry about security issues.

2021-07-09 18:01 UTC, kadatatlukishore commented
> > Hey @vybhav72954 , I made all the necessary changes. Only one security issue is there for `from lxml import html` line. I've used to parse html using xpath. So, most of the code has been written using it.
> 
> Don't worry about security issues.

Thanks @HarshCasper

2021-07-12 03:59 UTC, HarshCasper requested changes

2021-07-12 03:59 UTC, HarshCasper commented on Python/Fetch_Contributions/markdown_file.md
> +|    | Title to PR                                               | Link of PR                                                            | Status(Merged/Closed/Open)   |
Remove this file. It contains my contributions :sweat_smile:

2021-07-12 03:59 UTC, HarshCasper commented on Python/Fetch_Contributions/README.md
> +
Can you add a simple introduction in a few lines?

2021-07-12 03:59 UTC, HarshCasper commented on Python/Fetch_Contributions/README.md
> +|  0 | Format Code using Black                                   | https://github.com/moja-global/FLINT.Cloud/pull/22                    | Merged                       |
Remove this

2021-07-12 03:59 UTC, HarshCasper commented on Python/Fetch_Contributions/README.md
> +See [Here](https://github.com/kadatatlukishore/Rotten-Scripts/blob/fetch-pullrequests/Python/Fetch_Contributions/markdown_file.md)
Remove this

2021-07-12 03:59 UTC, HarshCasper commented on Python/Fetch_Contributions/README.md
> +
Remove unnecessary lines

2021-07-12 03:59 UTC, HarshCasper commented on Python/Fetch_Contributions/README.md
> +## Setup Instructions:
Add a line break

2021-07-12 03:59 UTC, HarshCasper commented on Python/Fetch_Contributions/README.md
> +The Code is written in Python 3.9. If you don't have Python installed you can find it [here](https://www.python.org/downloads/).
Remove this line

2021-07-12 03:59 UTC, HarshCasper commented on Python/Fetch_Contributions/README.md
> +**K Kishore**
Add a hyperlink to your LinkedIn/GitHub profile :wink:

2021-07-12 03:59 UTC, HarshCasper commented on Python/Fetch_Contributions/README.md
> +We will get the resuts in a file like **above** table.
Remove this line

2021-07-12 07:18 UTC, kadatatlukishore commented
Thanks for your inputs on this @HarshCasper . Made the necessary changes, please confirm. Thanks !

2021-07-13 04:15 UTC, HarshCasper approved these changes

2021-07-13 04:15 UTC, merged