added facebook request accepter
HarshCasper/Rotten-Scripts pull request #1184
Opened 2021-07-12 10:09 UTC by Sukriti-sood

Fixes #998 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation

2021-07-13 07:35 UTC, HarshCasper requested changes

2021-07-13 07:35 UTC, HarshCasper commented on Python/Fb_Request_Accepter/README.md
> +Script will accepts all the Friend requests on Your Facebook Account
Replace with `The Script will accept all your Friend Requests on your Facebook Account`

2021-07-13 07:35 UTC, HarshCasper commented on Python/Fb_Request_Accepter/README.md
> +https://imgur.com/a8HMZpq
Make it a GIF and embed it here

2021-07-27 16:24 UTC, iamakkkhil approved these changes
LGTM :)

2021-08-06 18:26 UTC, HarshCasper approved these changes

2021-08-06 18:26 UTC, merged