webcam sharing over a local server
HarshCasper/Rotten-Scripts pull request #1189
Opened 2021-07-22 05:54 UTC by HeyAnirudh

added a new python script to initiate sharing of webcam video in a local server using socket and pillow.

2021-07-27 16:11 UTC, RohiniRG commented
@HeyAnirudh please link an issue to the PR and try to follow the PR description template which was given

2021-07-27 16:53 UTC, HeyAnirudh reviewed
closes #1147

2021-08-04 14:04 UTC, kookee1226 approved these changes

2021-08-07 16:21 UTC, HarshCasper requested changes
Plagiarized from [here](https://pyshine.com/Socket-programming-and-openc/)

2021-08-07 16:21 UTC, closed without merging