added all files
HarshCasper/Rotten-Scripts pull request #1214
Opened 2021-08-10 18:19 UTC by kskrao219

# Description

Added the script which detects the motion in front of camera.

Fixes #(#1191)

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2021-08-30 04:21 UTC, HarshCasper requested changes
Additionally, format the code using Black

2021-08-30 04:21 UTC, HarshCasper commented on Python/Motion_Detection/script.py
> +
Remove the extra line

2021-08-30 04:21 UTC, HarshCasper commented on Python/Motion_Detection/script.py
> +    cv2.putText(img, text, (10, 20), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0, 0, 255), 2)
Draw the main logic of the code in a separate modular function

2021-08-30 04:21 UTC, HarshCasper commented on Python/Motion_Detection/README.md
> +- After running the above command , your camera will be launched if motion is detected it will show label as "Moving Object detected" otherwise "Normal"
Add a GIF/Screenshot (hosted on Imgur) to demonstrate the usage

2021-08-30 04:21 UTC, HarshCasper commented on Python/Motion_Detection/README.md
> +- Run command python3 script.py
Add backticks around the command

2021-08-30 04:21 UTC, HarshCasper commented on Python/Motion_Detection/README.md
> +- This script detection any kind of motion or movement infront of the camera.
Be slightly more descriptive

2021-10-03 09:02 UTC, HarshCasper commented
Closing the PR because of no updates.

2021-10-03 09:02 UTC, closed without merging

2021-10-03 13:16 UTC, kskrao219 commented
> Closing the PR because of no updates.
Hello @HarshCasper , i know its been a long time since this PR was done , and you also suggested me the changes to do past month, but due to some academic events since one month i was unable to do so , i request you to kindly give me some more time so that i can do the changes you suggested and revert back to you.