Added Intagram BOT #1296
HarshCasper/Rotten-Scripts pull request #1300
Opened 2022-03-01 17:00 UTC by harshitbansall

# Description

### This Python Script has the following functions:
* Download Profile Image from Username
* Download All Posts from Username
* Download Images from Hashtags

## Fixes #1296

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2022-03-02 04:37 UTC, HarshCasper requested changes
Looks pretty good to me.

Change the name of Python script to `instagram_bot.py`.

2022-03-02 04:37 UTC, HarshCasper commented on Python/Instagram_BOT/README.md
> +# 🍕 Instagram BOT - [Harshit Bansal](https://github.com/harshitbansall)
Removed the username from the title

2022-03-02 04:37 UTC, HarshCasper commented on Python/Instagram_BOT/README.md
> +## Prerequisites
Give a line break

2022-03-02 04:37 UTC, HarshCasper commented on Python/Instagram_BOT/README.md
> +## Usage
Give a line break

2022-03-02 04:37 UTC, HarshCasper commented on Python/Instagram_BOT/README.md
> +### If you liked this script and and used it, Please follow [Harshit Bansal](https://github.com/harshitbansall).
Just add an author section with a link to your profile. If someone is looking to follow, they would do it without being prompted.

2022-03-02 06:07 UTC, harshitbansall commented
@HarshCasper I've applied the changes you requested.

2022-03-05 18:20 UTC, HarshCasper approved these changes

2022-03-05 18:21 UTC, merged