Added Statuschecker script
HarshCasper/Rotten-Scripts pull request #1307
Opened 2022-03-02 17:56 UTC by casmpy

Fixes #1291

Added this script in BASH file

2022-03-03 13:13 UTC, HarshCasper requested changes
Can you add support for CSV & JSON as well with the output piped to a separate file possibly? It will help in situations where a lot of data is to be saved and following a terminal output might not be very conducive.

2022-03-03 17:38 UTC, casmpy commented
Okay I will see

2022-03-03 17:41 UTC, casmpy commented
@HarshCasper I have to see but you can merge it now

2022-03-04 04:58 UTC, HarshCasper commented
@casmpy That's not how it works — PRs that are reviewed should have those changes that are being requested by the maintainers. Otherwise, it won't make any sense to merge multiple PRs for the same stuff over and over again. If you are not willing to work on the changes, feel free to close the PR.

2022-03-04 06:41 UTC, casmpy commented
Okay I will do it

On Fri, Mar 4, 2022 at 10:28 AM Harsh Mishra ***@***.***>
wrote:

> @casmpy <https://github.com/casmpy> That's not how it works — PRs that
> are reviewed should have those changes that are being requested by the
> maintainers. Otherwise, it won't make any sense to merge multiple PRs for
> the same stuff over and over again. If you are not willing to work on the
> changes, feel free to close the PR.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/HarshCasper/Rotten-Scripts/pull/1307#issuecomment-1058829128>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APLCQISCD4I5YDFWVKGJNJTU6GKALANCNFSM5PYFXGFQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-11-11 11:39 UTC, closed without merging