Script to convert all HTML Files to Markdown Format #202
HarshCasper/Rotten-Scripts pull request #218
Opened 2020-08-18 08:54 UTC by tejan-singh

# Checklist:

- [X] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to undertand README
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests/screenshots(If any) that prove my fix is effective or that my feature works

2020-08-19 11:10 UTC, HarshCasper requested changes
Please make the apt changes

2020-08-19 11:10 UTC, HarshCasper commented on html-to-markdown/README.md
> +### This file uses module html2markdown
Create a proper Documentation Format

2020-08-19 11:10 UTC, HarshCasper commented on html-to-markdown/html_to_markdown.py
> +html_text = input("Paste HTML text here (eg. <p>this is stuff <strong>stuff</strong></p>): ")
You have to take in a HTML File and convert it to a Markdown File.

2020-08-19 11:10 UTC, HarshCasper commented on html-to-markdown/html_to_markdown.py
> +print (html2markdown.convert(html_text))
You need to save the content in a File. Not to display it on Console

2020-08-26 02:22 UTC, HarshCasper commented
Project Codebase has been optimized and modified right now. Please pull the new changes to your Fork and make a fresh PR.

2020-08-26 15:38 UTC, tejan-singh commented
I have been working on this. At least review this request and let me finish the task.

2020-08-27 05:53 UTC, closed without merging

2020-09-05 08:09 UTC, eternal-dreamer commented
Please review my pull requests . Changes have been updated.