Added scripts for automating sending messages in Telegram
HarshCasper/Rotten-Scripts pull request #324
Opened 2020-09-03 20:57 UTC by Namyalg

# Description

This script written in Python, can be used to automate the process of sending messages in Telegram

Fixes #323 

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2020-09-04 09:58 UTC, srimani-programmer commented on Automate-Telegram/automate_telegram.py
> +chrome_path = r"C:\Users\giril\AppData\Local\Programs\Python\Python36-32\chromedriver.exe"
```suggestion
# Ask for the user to enter the custom driver path. This script is not cross-platform compatible. It doesn't work in Linux and Unix based systems.
```

2020-09-04 09:59 UTC, srimani-programmer requested changes
Use the proper formatting guidelines to format the code and make the appropriate changes.!

2020-09-04 10:04 UTC, Namyalg commented
Okay, I will make the necessary changes.

On Fri, Sep 4, 2020, 3:29 PM Sri Manikanta Palakollu <
notifications@github.com> wrote:

> *@srimani-programmer* commented on this pull request.
> ------------------------------
>
> In Automate-Telegram/automate_telegram.py
> <https://github.com/HarshCasper/Rotten-Scripts/pull/324#discussion_r483517553>
> :
>
> > @@ -0,0 +1,50 @@
>
> +#Import and dependencies
>
> +from selenium import webdriver
>
> +import time
>
> +from selenium.webdriver.common.keys import Keys
>
> +
>
> +#Here the process of automation is achieved by using the framework Selenium.
>
> +#Selenium is a portable framework for testing and automating web applications web applications
>
> +
>
> +#Path to chromedriver.exe
>
> +chrome_path = r"C:\Users\giril\AppData\Local\Programs\Python\Python36-32\chromedriver.exe"
>
>
> ⬇️ Suggested change
>
> -chrome_path = r"C:\Users\giril\AppData\Local\Programs\Python\Python36-32\chromedriver.exe"
>
> +# Ask for the user to enter the custom driver path. This script is not cross-platform compatible. It doesn't work in Linux and Unix based systems.
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/HarshCasper/Rotten-Scripts/pull/324#pullrequestreview-482522877>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM3BEYPXUJGXZP66PCYQV2TSEC267ANCNFSM4QV5W7RQ>
> .
>

2020-09-04 10:45 UTC, Namyalg commented
I have made the necessary changes, I would like to know if I have to change anything

2020-09-04 14:28 UTC, srimani-programmer requested changes
This script will collapse if the user has a default driver path. please add the exception case for that.!

2020-09-04 14:28 UTC, srimani-programmer commented on Automate-Telegram/automate_telegram.py
> +            done = int(input("Enter 1 to continue, 0 to stop "))
```suggestion
            # Add the proper variable name

```

2020-09-04 18:34 UTC, Namyalg commented
I have made the changes

2020-09-12 05:19 UTC, HarshCasper commented
Looks good to me now! 

I am merging this!

2020-09-12 05:20 UTC, merged