Script to extract PDF Tables into CSV
HarshCasper/Rotten-Scripts pull request #354
Opened 2020-09-16 12:31 UTC by rutujadhanawade

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #284 

## Type of change

_Please delete options that are not relevant._

- [X] New feature (non-breaking change which adds functionality)

# Checklist:

- [X] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2020-09-16 12:32 UTC, rutujadhanawade commented
@HarshCasper Please review this.

2020-09-19 10:32 UTC, HarshCasper requested changes

2020-09-19 10:32 UTC, HarshCasper commented on Python/pdf_tables_extractor/PDFtoCSV.py
> +
Remove extra Lines of Code

2020-09-19 10:32 UTC, HarshCasper commented on Python/pdf_tables_extractor/PDFtoCSV.py
> +path = input("Enter the path to pdf file")
Instead of taking CLI inputs, is it possible to pass Argument Parsers to take the input?

2020-09-19 10:32 UTC, HarshCasper commented on Python/pdf_tables_extractor/PDFtoCSV.py
> +
Run the Code through PyLint and report the Quality Score

2020-09-19 10:32 UTC, HarshCasper commented on Python/pdf_tables_extractor/Readme.md
> +    pip install tabula-py
Format the README properly

2020-09-19 10:32 UTC, HarshCasper commented on Python/pdf_tables_extractor/output.csv
> +no,DAY,DATE,subject
We don't need a specific output CSV file.

2020-09-21 05:04 UTC, rutujadhanawade commented
@HarshCasper I have made all the changes.

![o](https://user-images.githubusercontent.com/53823042/93734210-f12c6800-fbf5-11ea-8ffe-f7484f7cef88.png)

2020-09-26 06:21 UTC, HarshCasper commented on Python/pdf_tables_extractor/Readme.md
> +         pip install tabula-py
Format them properly. You can mention them like `pip install tabula-py`

2020-09-26 06:21 UTC, HarshCasper commented on Python/pdf_tables_extractor/Readme.md
> +    python3 pdf_to_csv.py <no. of pages>
Format this part as well correctly

2020-09-26 06:21 UTC, HarshCasper requested changes
Kindly make these changes before final merge

2020-09-26 07:32 UTC, rutujadhanawade commented
Done :+1:  @HarshCasper

2020-09-29 06:32 UTC, merged