Base64 encoder and decoder in Python
HarshCasper/Rotten-Scripts pull request #359
Opened 2020-09-19 08:35 UTC by narayan2111

# Description

Python Script to Encode and Decode BASE 64 String to utf-8 string and vice versa.

Fixes #346 

## Type of change

_Please delete options that are not relevant._

- [Y] Bug fix (non-breaking change which fixes an issue)
- [Y] New feature (non-breaking change which adds functionality)

# Checklist:

- [Y ] My code follows the style guidelines(Clean Code) of this project
- [ Y] I have commented my code, particularly in hard-to-understand areas
- [Y ] I have created a helpful and easy to understand `README.md`

2020-09-19 08:35 UTC, narayan2111 commented
Kindly review this PR @seema1711 @HarshCasper

2020-09-19 10:30 UTC, HarshCasper requested changes

2020-09-19 10:30 UTC, HarshCasper commented on Python/Base64_Encoder_Decoder/README.md
> +# Python Script to Encode and Decode BASE 64 String to utf-8 string and vice versa.## About ScriptThis script is capable of converting some special/secret text into 64 BASE Encoded String ## To
Properly format the README. Take a look at other README to get a better idea on how you can format it up.

2020-09-19 10:30 UTC, HarshCasper commented on Python/Base64_Encoder_Decoder/ConvertToBase64.py
> +	string = input("Enter string to encode:")
Instead of taking CLI inputs, try to add Argument Parsers so that the input can be passed using Flags

2020-09-19 15:34 UTC, narayan2111 commented
I made the required changes 
Kindly Review This PR @HarshCasper

2020-09-20 05:02 UTC, narayan2111 commented
Kindly review this PR @HarshCasper

2020-09-20 09:51 UTC, merged

2020-09-20 09:51 UTC, HarshCasper commented
LGTM! 

Merged

2020-09-20 09:52 UTC, HarshCasper commented
@all-contributors bot please add @narayan2111 for code

2020-09-20 09:52 UTC, HarshCasper commented
@all-contributors bot please add @narayan2111 for documentation