Execution time scipt
HarshCasper/Rotten-Scripts pull request #385
Opened 2020-09-25 21:30 UTC by eternal-dreamer

# Description

Program to check timing.

Fixes #342 
Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2020-09-26 05:47 UTC, HarshCasper requested changes
Change the File Name as well.

2020-09-26 05:47 UTC, HarshCasper commented on Python/Execution time/execution.py
> +import time
Can you explain to me the utility of this file? 

I guess we can instead have this code sample in README to better explain others on how they can use this Script.

2020-09-26 05:47 UTC, HarshCasper commented on Python/Execution time/Readme.md
> +python execution.py
Format the README properly.

2020-09-26 05:47 UTC, HarshCasper commented on Python/Execution time/Readme.md
> +From stopwatch.py import Stopwatch class in your code
Format the File names correctly. You can mention them like `stopwatch.py`

2020-09-26 05:47 UTC, HarshCasper commented on Python/Execution time/Readme.md
> + Script to check how long task is running.
Add a proper description.

2020-09-27 13:31 UTC, eternal-dreamer commented
Please review it again

2020-10-02 06:28 UTC, merged