Image finder script is added
HarshCasper/Rotten-Scripts pull request #419
Opened 2020-10-02 14:04 UTC by gupta-piyush19

# Description

This script generates images for blogs of any genre. Just give the category/genre name you want

Fixes #336 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update
- [x] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2020-10-02 14:06 UTC, gupta-piyush19 commented
@HarshCasper I've created this new PR, kindly review and merge this one.

2020-10-03 04:45 UTC, HarshCasper requested changes

2020-10-03 04:45 UTC, HarshCasper commented on JavaScript/Blog_Image_Finder/ImageFinder.js
> +let key = 'fjWKDve02zbReHxiCHd9mwClRzeA-3KRHTC6XlCRz0I';
Don't keep your Secret Keys in your Project. That's detrimental since it can be exploited by others. Keep your Credentials in .env file and add the .env in .gitignore

2020-10-03 05:28 UTC, gupta-piyush19 commented on JavaScript/Blog_Image_Finder/ImageFinder.js
> +let key = 'fjWKDve02zbReHxiCHd9mwClRzeA-3KRHTC6XlCRz0I';
@HarshCasper Is this(https://www.youtube.com/watch?v=17UVejOw3zA) the correct way to do the same? I've never used .env file.

2020-10-03 06:28 UTC, gupta-piyush19 commented on JavaScript/Blog_Image_Finder/ImageFinder.js
> +let key = 'fjWKDve02zbReHxiCHd9mwClRzeA-3KRHTC6XlCRz0I';
@HarshCasper I am closing this PR, and created another PR in which API key is not present. I was facing issues related to git that's why I've created a new one, really sorry for all the inconveniences caused.

2020-10-03 06:28 UTC, closed without merging