Get bbc news
HarshCasper/Rotten-Scripts pull request #460
Opened 2020-10-07 07:09 UTC by KhushalPShah

# Description

Added a script to get the latest news from the BBC News Web API.
It provides the headlines as well as the links to read the full article.

Fixes #(https://github.com/HarshCasper/Rotten-Scripts/issues/457)

## Type of change

_Please delete options that are not relevant._

- [*] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2020-10-07 07:16 UTC, KhushalPShah commented
Can someone tell me why is the check failing ? 
PS : I am new to open source, and hence not sure of this issue.

Thanks!

2020-10-08 08:30 UTC, HarshCasper requested changes

2020-10-08 08:30 UTC, HarshCasper commented on Python/Get_BBC_News/getNews.py
> +    main_url = " https://newsapi.org/v1/articles?source=bbc-news&sortBy=top&apiKey=4dbc17e007ab436fb66416009dfb59a8"
You should never be keeping your API Key on your Source Code. Create a `.env` file and make use of `Dotenv` module to pass secret information to your code. Make sure to add a `.env.example` to help other developers know that they can keep their secret keys into that.

2020-10-08 08:30 UTC, HarshCasper commented on Python/Get_BBC_News/getNews.py
> +    for ar in articles:
Make use of meaningful variable names. `ar` doesn't seem to be consistent with any naming convention.

2020-10-08 08:30 UTC, HarshCasper commented on Python/Get_BBC_News/getNews.py
> +
Remove these trailing lines.

2020-10-08 08:30 UTC, HarshCasper commented on Python/Get_BBC_News/getNews.py
> +    NewsFromBBC()
Run your Code through PyLint and see what improvements you can do depending on your score.

2020-10-08 10:33 UTC, KhushalPShah commented
Have added a new commit.
Please check and let me know if there are some more things missing from my side.

Thanks @HarshCasper  for the help!

2020-10-08 10:37 UTC, KhushalPShah commented
Have added a new commit.
Please check and let me know if there are some more things missing from my side.

Thanks @HarshCasper for the help!

2020-10-13 15:05 UTC, KhushalPShah commented
Is there anything more to be done here @HarshCasper ?
If not, can you merge this?

2020-10-16 04:04 UTC, HarshCasper commented
Great Work @KhushalPShah

2020-10-16 04:07 UTC, merged