Add DSC_event_scraper
HarshCasper/Rotten-Scripts pull request #462
Opened 2020-10-07 18:57 UTC by DevChoganwala

# Description

This scripts scrapes all the events available on the DSC community website and outputs them in a file called data.csv (located in the same directory as your script).
Modules Used: `requests`, `csv`, `sys`, `json`

Fixes #452 

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# Checklist:

- [X] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2020-10-07 19:01 UTC, DevChoganwala commented
@HarshCasper Please let me know if I have pulled requests incorrectly since I am new to contributing. I will make appropriate changes. Thank you.

2020-10-08 08:21 UTC, HarshCasper requested changes

2020-10-08 08:21 UTC, HarshCasper commented on Python/DSC_event_scraper/event_scraper.py
> +
Remove these extra lines

2020-10-08 08:21 UTC, HarshCasper commented on Python/DSC_event_scraper/event_scraper.py
> +        if(url == None): #url = None when there is no further page
Keep the Comment above the Line of Code

2020-10-08 08:21 UTC, HarshCasper commented on Python/DSC_event_scraper/event_scraper.py
> +import json
I don't think that the imports are properly stacked up. Can you try running your Script through PyLint and review what changes you can do here?

2020-10-08 08:21 UTC, HarshCasper commented on Python/DSC_event_scraper/event_scraper.py
> +            response.raise_for_status() #if exceptions raised quit the program
Kindly keep the Single Line Comment above the line of code

2020-10-08 18:25 UTC, DevChoganwala commented
@HarshCasper I have made the above commented changes to my script. Please check if I need to make more changes before merging. Thanks you.

2020-10-16 04:42 UTC, merged

2020-10-16 04:42 UTC, HarshCasper commented
give @DevChoganwala 75 points