Added Script to generate valid google search url with required parame…
HarshCasper/Rotten-Scripts pull request #493
Opened 2020-10-18 12:11 UTC by GoswamiTushar

# Description

URL Generator is an independent script with scope of adding more functionality for other search engines as well. 
It takes the search query as input and returns the well formatted URL string.

Fixes #(461)

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2020-10-21 15:38 UTC, HarshCasper commented
@seema1711 I would like if you can go over these Scripts because I feel that I might be missing a lot of details in here, in an otherwise brilliant execution

2020-10-23 04:07 UTC, HarshCasper requested changes
Can you try running your Code through PyLint and improving on the pointers given by the Tool? Also kindly add a Screenshot/GIF in your README to help better understand on how your Script works.

2020-10-23 04:07 UTC, HarshCasper commented on Python/Tags_Scraper/Requirements.txt
> +Libraries which will be required and need to be installed are:
You don't need to add this line in your `requirements.txt`

You can generate a Requirements File via `pip freeze` and remove all the unnecessary lines.

2020-10-23 04:07 UTC, HarshCasper commented on Python/Tags_Scraper/Readme.md
> +- **Main** : Main module is what we need to interact with. It combines the functionality of other three modules into 1 whole. The data generated is Stored in KeywordsData.txt file.
Can you add a brief note on how to run your Scripts?

2020-10-23 04:07 UTC, HarshCasper commented on Python/Tags_Scraper/Fetch_Tags.py
> +		# print(soup.prettify())
You can remove the Commented Code.

2020-10-23 04:07 UTC, HarshCasper commented on Python/Tags_Scraper/Fetch_Tags.py
> +
Remove the Blank Lines of Code

2020-10-27 12:15 UTC, HarshCasper commented
@GoswamiTushar Are you working on this? Kindly let me know so that I can award you the points for the same aptly.

2020-10-27 12:24 UTC, GoswamiTushar commented
> @GoswamiTushar Are you working on this? Kindly let me know so that I can award you the points for the same aptly.

Yes I'm working on it. 
I'm using pylint for the first time so its taking a bit time to optimise code in a way that it gets score over 8.
I'll get it done by 29 oct

2020-11-07 18:02 UTC, closed without merging