Added the code to toonify any image
HarshCasper/Rotten-Scripts pull request #565
Opened 2020-12-03 05:21 UTC by Tejas1510

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #562

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2020-12-03 16:12 UTC, Tejas1510 commented
@HarshCasper can you please review the pull request

2020-12-07 06:22 UTC, HarshCasper requested changes
The Code looks good to me! 

Please make the below changes and it would be ready to merge!

2020-12-07 06:22 UTC, HarshCasper commented on Python/ToonifyImage/toonify.py
> +api_key=input("Please enter your api key")
Please have the API Key in a `.env` file and use a module like dotenv to import them in your Python Code

2020-12-07 06:22 UTC, HarshCasper commented on Python/ToonifyImage/toonify.py
> +imagePath=input("Please enter the path of image to toonify : ")
Can you try passing it via arguments instead of dynamic input?

2020-12-07 18:22 UTC, Tejas1510 commented
@HarshCasper I have made changes taking input as an argument instead of dynamic input, all the comments are added above the code, Just the part of API in env I don't have an idea about it.
Rest I have done
Please Give it a look

2020-12-11 07:01 UTC, HarshCasper commented
Hello @Tejas1510 

That's easy. Let me explain: 

- Have a `.env` file in your Directory and add the following: 

```
API_KEY = "XXXXXXXXXXXXXXXXXXXXXXX"
```

- Install a Package named `decouple` to get the Environment Variables. Import it like this: 

`
from decouple import config
`

- Go to your Main Script and add the following line of code: 

`
api_key = config("API_KEY")
`

You are now ready to use the API Key in your Code. Do not push the `.env` in your Code because its not a good practise. Have a `.env.example` which the User can rename to `.env` and store their API Key. Have the `.env.example` for sure.

2020-12-11 07:45 UTC, Tejas1510 commented
Hey @HarshCasper thanks for explaining the concept of .env file in a very simpler way
I have added the .env.example file as asked by you so the user can store their API here and use it main code
I have also updated the main file by the using  CONFIG
Please review if everything is all right

2020-12-17 09:13 UTC, HarshCasper commented
LGTM!

2020-12-17 09:13 UTC, merged

2020-12-17 15:16 UTC, Tejas1510 commented
@HarshCasper  Can you please update the leaderboard with the point associated with merged PR