Added OTP verifier python script
HarshCasper/Rotten-Scripts pull request #574
Opened 2020-12-05 11:57 UTC by Ash515

# Description

Added OTP verifier python Script.

2020-12-07 05:02 UTC, HarshCasper commented on Python/OTP_verifier.py
> +account_sid='Find from your twilio account'
Keep this in a `.env` file and use a module like `dotenv` to import them in your Scipt. It makes it easy for us to track the Environment Variables.

2020-12-07 05:09 UTC, HarshCasper requested changes
Please add a proper README as well with instructions on kick-starting the Script.

2020-12-07 05:09 UTC, HarshCasper commented on Python/OTP_verifier.py
> +otp=random.randint(1000,9999)
The Random Generatic Logic is not that secure and strong, as far as I understand. You can take a look at this [blog](https://realpython.com/python-random/) for better understanding.

2020-12-07 05:09 UTC, HarshCasper commented on Python/OTP_verifier.py
> +message=client.message.create(
The Code seems to be unformatted. Format your Code properly and indent it for better understanding.

2020-12-11 07:01 UTC, HarshCasper commented
Are you still working on the same?

2020-12-11 07:57 UTC, Ash515 commented
No I have practical examination so I not go to that repo. Tomorrow I will
get free and start to solve those problems

On Fri, 11 Dec, 2020, 12:31 PM Harsh Bardhan Mishra, <
notifications@github.com> wrote:

> Are you still working on the same?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/HarshCasper/Rotten-Scripts/pull/574#issuecomment-743015384>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMVM2IWDM67WOKON4LITGLTSUG7VLANCNFSM4UOP6UOA>
> .
>

2020-12-17 09:52 UTC, HarshCasper commented
Hello @Ash515 

I am closing this PR right now. If you are still looking to work on the same, feel free to ping me up and I will open it up 👍

2020-12-17 09:52 UTC, closed without merging