Merge two PDF Script
HarshCasper/Rotten-Scripts pull request #611
Opened 2020-12-17 16:00 UTC by Tejas1510

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #565

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2020-12-17 16:01 UTC, Tejas1510 commented
@HarshCasper Please Give it a review

2020-12-18 03:48 UTC, HarshCasper requested changes
Remove the PDF Files. The Script works good and that is enough!

2020-12-18 03:48 UTC, HarshCasper commented on Python/mergetwopdf/Readme.MD
> +# Merge two pdf Files
Rename the `mergetwopdf` to `merge_two_pdf` to make it look more readable and concise.

2020-12-18 03:48 UTC, HarshCasper commented on Python/mergetwopdf/Readme.MD
> +4. you will get the merged pdf in the same directory
Add proper commands to run the Script. Many people are not familiar with Argument Parsers. This would be helpful for them in the longer run.

2020-12-18 03:48 UTC, HarshCasper commented on Python/mergetwopdf/Readme.MD
> +You can check the final output in MergedFiles.pdf File
Can you add a GIF probably showing the output. You can make use of an extension called `Awesome Screenshot` (not an Ad 😆 ) but it is real handy to capture screen and convert into GIF for the purpose.

2020-12-18 03:48 UTC, HarshCasper commented on Python/mergetwopdf/merge.py
> +file2=sys.argv[2]
Format the spaces around the operators

2020-12-29 11:32 UTC, HarshCasper commented
Are you working on it @Tejas1510 

If not, I can close this PR and let someone take up the Issue to solve this.

2020-12-29 11:41 UTC, Tejas1510 commented
@HarshCasper sorry the delay 
I will make a pr soon within next 1 hour

2020-12-29 12:28 UTC, Tejas1510 commented
@HarshCasper I have made the following changes
I have added the GIF required
Remove unwanted files
Add proper spacing

2020-12-31 08:09 UTC, HarshCasper commented
Thanks. LGTM 👍

2020-12-31 08:09 UTC, merged

2021-01-03 16:06 UTC, Tejas1510 commented
@HarshCasper can you please update the NWoC 2020 Leaderboard with the points associated with merged PR as the open-source program is coming to an end so it will matter in the leaderboard

2021-01-05 15:14 UTC, HarshCasper commented
> @HarshCasper can you please update the NWoC 2020 Leaderboard with the points associated with merged PR as the open-source program is coming to an end so it will matter in the leaderboard

Can you do a quick math and let me know your scores?

2021-01-05 15:55 UTC, Tejas1510 commented
94 + 15 = 109