Mohta_rahul_branch cryptocurrency converter fixes issue #427
HarshCasper/Rotten-Scripts pull request #615
Opened 2020-12-20 10:58 UTC by Rahul555-droid

# Description
Created a script crypto_converter.py
This script can be used as a cryptocurrency to currency converter or vice versa using functions in the code. 
It uses coinbase API.
Fixes #(427)

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2020-12-29 12:06 UTC, HarshCasper requested changes

2020-12-29 12:06 UTC, HarshCasper commented on Python/cryptocurrency_converter/crypto_converter.py
> +    convert_crypto_to_currency(1, 'BTC', 'USD'), 'USD', 'BTC'))
Change the Static Input to Dynamic Input. Take the input from the User instead of passing it as a Driver Code.

2020-12-29 12:06 UTC, HarshCasper commented on Python/cryptocurrency_converter/README.md
> +##Crypto Currency Converter
There should be a space after `##` to have the Heading Tag do its trick.

2020-12-29 12:06 UTC, HarshCasper commented on Python/cryptocurrency_converter/README.md
> +    *getting exchange rates through coinbase API is free and doesn't requires an API key.
Left-Align them. Take a look at other READMEs to find how to have a good Doc for your Script.

2020-12-29 12:06 UTC, HarshCasper commented on Python/cryptocurrency_converter/crypto_converter.py
> +    # "BTC" is for Bitcoin,"ETH" is for Ethirium and so on
Typo. It should be `Ethereum` not `Ethirium`

2020-12-29 14:12 UTC, Rahul555-droid commented
Hi @HarshCasper  did the changes in the script and readme file.

2020-12-31 08:03 UTC, HarshCasper approved these changes

2020-12-31 08:03 UTC, merged