added the readme_generator_tool in the readme file
HarshCasper/Rotten-Scripts pull request #638
Opened 2020-12-29 16:42 UTC by hr1shu

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #583 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2020-12-29 16:44 UTC, hr1shu commented
Please guide me to how to fix the  above issue

2020-12-31 04:33 UTC, HarshCasper requested changes

2020-12-31 04:33 UTC, HarshCasper commented on README.md
> +Try the tool: [GitHub Profile README Generator](https://rahuldkjain.github.io/gh-profile-readme-generator)
We don't need this. 

Maybe you had a very wrong conception around the Issue. I was perhaps looking for a Script that can generate a Profile README for the User and then push it to Github. We don't want our main README to be an advert for the tool. 

I'm sorry but I would not be able to merge the PR with this right here!

2020-12-31 04:33 UTC, HarshCasper commented on Python/Password Checker/Password-checker.py
> +
Name of the Directory should be `Password_Checker` and not `Password Checker`

2020-12-31 04:33 UTC, HarshCasper commented on Python/Password Checker/Password-checker.py
> +
Remove the extra line of Code

2020-12-31 04:33 UTC, HarshCasper commented on Python/Password Checker/Password-checker.py
> +  response = request_api_data(first5_char)
Add proper Comments right here!

2020-12-31 04:33 UTC, HarshCasper commented on Python/Password Checker/Password-checker.py
> +      return count
Add proper Comments!

2020-12-31 04:33 UTC, HarshCasper commented on Python/Password Checker/Password-checker.py
> +def request_api_data(query_char):
Add Docstrings to the functions.

2020-12-31 04:33 UTC, HarshCasper commented on Python/Password Checker/Password-checker.py
> +def get_password_leaks_count(hashes, hash_to_check):
Add Docstrings to the functions.

2020-12-31 04:33 UTC, HarshCasper commented on Python/Password Checker/Password-checker.py
> +def pwned_api_check(password):
Add Docstrings to the functions.

2020-12-31 04:33 UTC, HarshCasper commented on Python/Password Checker/README.md
> +It's pretty cool.
Don't break your statement too often. Use full statements. And we definitely don't need "It's pretty cool" on the README. Follow the standard mentioned [here](https://github.com/HarshCasper/Rotten-Scripts/blob/master/TEMPLATE_README.md) and stick to the point.

2020-12-31 04:33 UTC, HarshCasper commented on Python/Password Checker/README.md
> +If that's not the case `pip  install request` will do the job.
Add a `requirements.txt` file and ask the User to install packages from there, for the purpose.

2020-12-31 04:33 UTC, HarshCasper commented on Python/Password Checker/README.md
> +The script has proper comments which should be followed. The script is easy to use.
Redundant! Please remove this.

2020-12-31 04:33 UTC, HarshCasper commented on Python/Password Checker/README.md
> +
Remove extra lines.

2020-12-31 07:26 UTC, hr1shu commented
I'm sorry for the trouble mate.

2020-12-31 07:26 UTC, closed without merging

2021-01-07 15:37 UTC, HarshCasper commented
> I'm sorry for the trouble mate.

I don't understand the reason behind making and closing a PR after a review. You could have improved on it, at best. Anyways, Open-Source Contribution are all about voluntary contributions and learning out of the same ✌️