Python docscanner
HarshCasper/Rotten-Scripts pull request #654
Opened 2020-12-31 14:41 UTC by djm-1

# Python docscanner

converting image files into docscanner like .jpg output using opencv

Fixes #640

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2020-12-31 14:50 UTC, djm-1 commented
why is it showing failed?

2021-01-03 11:27 UTC, HarshCasper commented
I still don't understand the purpose of Script much 😕 

Are you converting every Image to a JPG format? Or am I reading it wrong? 

Nevertheless, forget about the failing tests and please add apt information on your README and Code to help me better understand. I will review the Code once its done 👍

2021-01-03 13:05 UTC, djm-1 commented
> 
> 
> I still don't understand the purpose of Script much 😕
> 
> Are you converting every Image to a JPG format? Or am I reading it wrong?
> 
> Nevertheless, forget about the failing tests and please add apt information on your README and Code to help me better understand. I will review the Code once its done 👍

I have updated the description.

2021-01-05 12:14 UTC, HarshCasper commented
Thanks @djm-1 for updating the description. Please update your README as well according to the same 👍 

Moreover, we have a standard template that we follow. Please follow that. And remove Images from the commits. The Repository is getting heavier and I am potentially looking for solutions to make it lighter.

2021-01-05 13:09 UTC, djm-1 commented
@HarshCasper I have modified it. Please label it for Devscript winter of code (on successful merging). Thank you.

2021-01-07 10:30 UTC, djm-1 commented
Sir, please review my PR

2021-01-07 15:31 UTC, HarshCasper requested changes

2021-01-07 15:31 UTC, HarshCasper commented on Python/Docscanner_Python/script.py
> +filename=input('enter file name : ')
Can you use Arg Parse instead of asking User to enter file name?

2021-01-07 15:31 UTC, HarshCasper commented on Python/Docscanner_Python/script.py
> +cv2.imwrite('output.jpg',th1)
You can ask for the Output Image Name from the User itself

2021-01-07 15:31 UTC, HarshCasper commented on Python/Docscanner_Python/README.md
> +Github username : djm-1
Add a hyper-link to your name with your Github Profile, if you want to be credited with your Script

2021-01-13 04:41 UTC, HarshCasper commented
Are you working on this @djm-1 ?

2021-01-29 05:43 UTC, closed without merging