Added location based on IP Address Script
HarshCasper/Rotten-Scripts pull request #679
Opened 2021-01-07 17:23 UTC by pankaj892

#666 resolved

2021-01-07 17:31 UTC, pankaj892 commented
@HarshCasper review the PR and merge the changes

2021-01-11 10:30 UTC, pankaj892 commented
I see the PR hasn't been merged yet is there any issue with the PR @HarshCasper

2021-01-13 04:29 UTC, HarshCasper requested changes
Do we actually need to have a script for this? 

It's just a moderate import and use of pre-built function to try out the lookup.

2021-01-13 04:29 UTC, HarshCasper commented on README.md
> +    <td align="center"><a href="https://github.com/pankaj892"><img src="https://avatars3.githubusercontent.com/u/31444506?v=4" width="100px;" alt=""/><br/><sub><b>Pankaj Biradar</b></sub></a><br /><a
You don't need to make this change manually. The All Contributors Bot does this for us, automatically.

2021-01-13 04:29 UTC, HarshCasper commented on Python/Get_location_based_on_IP_Address/locationip.py
> +print(ipInfo)
Add a new line at the EOF.

2021-01-13 14:33 UTC, pankaj892 commented
@HarshCasper  i have made the necessary changes please review them

2021-01-14 03:58 UTC, HarshCasper commented
I am still not able to understand the purpose of the Script. Also, you have not added any README to show how the Script works.

2021-01-14 16:31 UTC, pankaj892 commented
@HarshCasper  the Script gives the location of a user along with details like Country Code,Telecom Operator based on the user's IP Address

2021-01-18 16:52 UTC, pankaj892 commented
@HarshCasper I see the PR hasn't been merged did i do any mistake

2021-01-22 12:45 UTC, HarshCasper commented
> @HarshCasper I see the PR hasn't been merged did i do any mistake

Make README changes and add an apt description about your Script with some screenshots as well

2021-01-23 05:21 UTC, closed without merging