[Bash] Empty Subtitles
HarshCasper/Rotten-Scripts pull request #704
Opened 2021-01-16 14:53 UTC by KamalDGRT

# Description

Bash script to generate subtitles for video files.

Fixes #664 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2021-01-22 13:00 UTC, HarshCasper requested changes
Make apt README changes for the BASH directory

2021-01-29 05:53 UTC, HarshCasper commented
@KamalDGRT Are you working on the same?

2021-01-29 11:16 UTC, KamalDGRT commented
I will make the PR by tomorrow evening!

2021-02-02 11:15 UTC, HarshCasper approved these changes

2021-02-02 11:16 UTC, merged