No Subtitles Matroska
HarshCasper/Rotten-Scripts pull request #708
Opened 2021-01-20 13:16 UTC by KamalDGRT

# No Subtitles Matroska

Bash script to remove subtitles from matroska (mkv) files present in a directory.

Fixes #658 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2021-01-23 03:03 UTC, HarshCasper requested changes

2021-01-23 03:03 UTC, HarshCasper commented on Bash/Multiplexing/No_Subtitles_MKV/README.md
> +![Command Execution](https://github.com/KamalDGRT/static/blob/master/RottenScripts/img/03_nosubsmkv_command.png)
Can you please upload the Images on Imgur and reference them here?

2021-01-23 03:03 UTC, HarshCasper commented on Bash/Multiplexing/No_Subtitles_MKV/README.md
> +![Checking](https://github.com/KamalDGRT/static/blob/master/RottenScripts/img/04_trackinfo_original.png)
Can you please upload the Images on Imgur and reference them here?

2021-01-23 03:03 UTC, HarshCasper commented on Bash/Multiplexing/No_Subtitles_MKV/README.md
> +![Checking](https://github.com/KamalDGRT/static/blob/master/RottenScripts/img/05_trackinfo_new.png)
Can you please upload the Images on Imgur and reference them here?

2021-01-29 05:53 UTC, HarshCasper commented
@KamalDGRT Are you working on the same?

2021-01-29 11:15 UTC, KamalDGRT commented
I will make the PR by tomorrow evening!

2021-02-02 11:16 UTC, HarshCasper approved these changes

2021-02-02 11:17 UTC, merged