chrome dino game automation in python
HarshCasper/Rotten-Scripts pull request #724
Opened 2021-01-27 17:53 UTC by oshi36

# Description

I had used python to automate chrome dinosaur game using pyautogui and pillow .

Fixes #(713)

## Type of change
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

2021-01-29 05:57 UTC, HarshCasper commented
Few Changes before the PR is reviewed: 

- Add a README to document your Code/Approach 
- Add Screenshots/GIF to show that your Script is working 
- Make apt changes on the Python README 
- Put Comments/Docstrings on the Code

2021-01-29 08:30 UTC, oshi36 commented
@HarshCasper  I had done the above mentioned changes .

2021-02-10 06:26 UTC, HarshCasper requested changes
Please take a look at some other docs for various scripts to see on how you can format your doc. The Code look good to me 👍

2021-02-10 06:26 UTC, HarshCasper commented on Python/chromedino_script/README.md
> +To know the location of the obstacles first we need to find the X and Y locations of them on screen . Check coordinates.py file
Can you make this more relevant? 

Usually follow this pattern while documenting your Code: 

- What does your Script does? 
- The files in them and their individual roles (Don't ask the user to check coordinates.py file) 
- Requirements to run these Scripts (Place them in a `requirements.txt` file

2021-02-10 06:26 UTC, HarshCasper commented on Python/chromedino_script/README.md
> +After running the main.py file go to chrome browser where dino game is opened(chrome://dino) and then start game by pressing space bar and it will play automatically.
Can you add proper step-wise instructions to run the scripts?

2021-02-10 06:26 UTC, HarshCasper commented on Python/chromedino_script/README.md
> +So , we have to match the gray pixels and if obstacle  is close to dino then  make a jump. For this take a image with obstacles coming in between using ImageGrab from pillow library and then find out
Use a Checker like Grammarly to verify if the content is consistent. Highlight the file names

2021-02-14 14:54 UTC, HarshCasper approved these changes

2021-02-14 14:54 UTC, merged

2021-02-14 14:54 UTC, HarshCasper commented
@all-contributors please add @oshi36 for code

2021-02-14 14:54 UTC, HarshCasper commented
@all-contributors please add @oshi36 for documentation