PDF reorder pull request.
HarshCasper/Rotten-Scripts pull request #749
Opened 2021-02-11 11:29 UTC by Rahul555-droid

# Description

The pdf reorder script. Did the changes to the readme file and moved images to imgur.

Fixes #610 

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update
- [x] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2021-02-11 11:30 UTC, Rahul555-droid commented
@HarshCasper Sorry dude was busy with exams and also my laptop had some issues.
Created a new local repo and i am sending the PR again.

This issue and PR has stretched way long lol

I think this should work :)

2021-02-12 08:40 UTC, HarshCasper requested changes

2021-02-12 08:40 UTC, HarshCasper commented on Python/PDF_reorder/README.md
> +## About the script pdf_reorder_.py
Just keep `About the Script`

2021-02-12 08:40 UTC, HarshCasper commented on Python/PDF_reorder/pdf_reorder_.py
> +"""
That's not how Docstrings are used. Refer this: https://www.programiz.com/python-programming/docstrings

2021-02-12 08:40 UTC, HarshCasper commented on Python/PDF_reorder/pdf_reorder_.py
> +    # Initialising the writer object using the PdfWriter class,from this we would create a new modified Pdf
Reduce the length of the line

2021-02-12 08:40 UTC, HarshCasper commented on Python/PDF_reorder/pdf_reorder_.py
> +    dic = {curr: new for curr, new in lst}
Unnecessary use of comprehension

2021-02-28 04:46 UTC, HarshCasper commented
Are you working on this @Rahul555-droid ?

2021-03-03 11:31 UTC, HarshCasper commented
Closing this PR because of no updates.

2021-03-03 11:31 UTC, closed without merging