Added Github_Unfollowers Script
HarshCasper/Rotten-Scripts pull request #774
Opened 2021-02-18 20:30 UTC by vismitap

Fixed #732

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.
This is a script to track recent unfollowers on github.
Fixes #732 

## Type of change

_Please delete options that are not relevant._

- [x ] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

Output:
![output](https://i.imgur.com/R1pYphi.png)

2021-02-18 20:32 UTC, vismitap commented
Hey! Forgot to edit the main README.md and add my name. Doing one commit for that!

2021-02-20 07:32 UTC, HarshCasper requested changes
Exceptional work. Requested for some minor changes. 

Thanks!

2021-02-20 07:32 UTC, HarshCasper commented on JavaScript/Github_unfollowers/.gitignore
> +node_modules
Please remove the `.gitignore`. We have a global `.gitignore` to cover everything up :)

2021-02-20 07:32 UTC, HarshCasper commented on JavaScript/Github_unfollowers/Github_Unfollowers.js
> +// Script to track recent unfollowers on github using github api
Replace `Script to track recent unfollowers on github using github api` to `Script to track recent people who unfollowed you on Github using the Github API`

2021-02-20 07:32 UTC, HarshCasper commented on JavaScript/Github_unfollowers/Github_Unfollowers.js
> +  .catch((err) => console.log(err));
Add a new line at the EOF

2021-02-20 07:32 UTC, HarshCasper commented on JavaScript/Github_unfollowers/Github_Unfollowers.js
> +      console.log("Run for the first time.");
Use a more friendly terminal statement like: `Analyzed and Run for the first time`

2021-02-20 07:32 UTC, HarshCasper commented on JavaScript/Github_unfollowers/README.md
> +This is a script to track recent unfollowers on github.
Replace this with `Github Unfollowers is a Script to track the recent accounts who unfollowed you on Github`

2021-02-20 07:32 UTC, HarshCasper commented on JavaScript/Github_unfollowers/README.md
> +* The data is then stored in old.json file and compared with new data and hence the unfollowers can be found!
Use backticks for `old.json` file. If possible you can replace this with a more friendly or understanding filename, though that's entirely optional

2021-02-20 07:32 UTC, HarshCasper commented on JavaScript/Github_unfollowers/README.md
> +![Run Second Time](blob:https://imgur.com/d45a7353-de3b-420e-a459-16670c0f62ca)
This doesn't work. Can you optimize this?

2021-02-20 10:03 UTC, vismitap commented
Sure! I will do the changes and revert back 🤩👍

2021-02-20 12:55 UTC, vismitap commented
Hey! Messed up something really badly.  I will make a fresh PR with all those changes. Sorry for the inconvenience.😓

2021-02-22 07:34 UTC, closed without merging