Get-Wifi passwords
HarshCasper/Rotten-Scripts pull request #801
Opened 2021-02-28 12:12 UTC by pritamp17

# Description
Python Script which will send all stored wifi passwords on windows pc to the given email.

Fixes #800 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change
- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of myown code
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

![final-1](https://user-images.githubusercontent.com/65030567/109418035-35fdcb80-79ec-11eb-8697-b24e64fc82e6.jpg)
![final-2](https://user-images.githubusercontent.com/65030567/109418037-3a29e900-79ec-11eb-9ec3-8e63c5e11b94.jpg)

2021-02-28 14:10 UTC, HarshCasper commented
Why is the Anime Scraper and the Wifi Password script added into the PR?

2021-02-28 14:14 UTC, pritamp17 commented
Sorry for that😅 i will make corrections shortly..

On Sun, 28 Feb 2021, 7:40 pm Harsh Mishra, <notifications@github.com> wrote:

> Why is the Anime Scraper and the Wifi Password script added into the PR?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/HarshCasper/Rotten-Scripts/pull/801#issuecomment-787458527>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APQETJ7TNQSHH7CH42X3MNLTBJFGPANCNFSM4YK74AUA>
> .
>

2021-02-28 16:12 UTC, pritamp17 commented
@HarshCasper I have deleted the Anime tracker folder, do I need to make any other changes?

2021-03-02 07:18 UTC, sohamsshah requested changes
Great work @pritamp17 

Please rename `Get-Wifi-Password` to `Get_Wifi_Password` as to follow the naming conventions at the repository.

2021-03-03 11:50 UTC, HarshCasper requested changes

2021-03-03 11:50 UTC, HarshCasper commented on Python/Get-Wifi-Password/finder.py
> +def send_mail(email,password,message):
Add a Doctext

2021-03-03 11:50 UTC, HarshCasper commented on Python/Get-Wifi-Password/finder.py
> +	server = smtplib.SMTP("smtp.gmail.com",587)
Can this be captured in a `.env` file?

2021-03-03 11:50 UTC, HarshCasper commented on Python/Get-Wifi-Password/finder.py
> +
Can we have separate function for basic setup and a separate one for the driver code?

2021-03-03 11:50 UTC, HarshCasper commented on Python/Get-Wifi-Password/finder.py
> +      listi.append("{:<30}|  {:<}".format(i, ""))
Can you aptly document this part?

2021-03-30 10:46 UTC, vybhav72954 commented
@pritamp17 can you provide us with updates

2021-03-31 09:09 UTC, closed without merging