Bitcoin Price Tracking Python Script
HarshCasper/Rotten-Scripts pull request #802
Opened 2021-02-28 12:29 UTC by pritamp17

# Description
Track Bitcoin Price In Real-Time.
Fixes #789
## Type of change
- [ ] New feature (non-breaking change which adds functionality)
# Checklist:
- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2021-02-28 16:32 UTC, pritamp17 commented
@HarshCasper could you review this PR?

2021-03-02 07:09 UTC, sohamsshah requested changes
@pritamp17 This looks good and clean. Good work! 

Would suggest a few changes:
* Rename `BITCOIN-price-tracker` to `Bitcoin_Price_Tracker`
* You can use Python `f-strings` instead of concatenation wherever possible in the code.

2021-03-03 11:51 UTC, HarshCasper requested changes

2021-03-03 11:51 UTC, HarshCasper commented on Python/BITCOIN-price-tracker/tracker.py
> +def get_latest_crypto_price(coin):
Put a Docstring

2021-03-03 11:51 UTC, HarshCasper commented on Python/BITCOIN-price-tracker/tracker.py
> +print('BITCOIN price : ' + price)
Enclose this in a `if __name__ == '__main__'` block

2021-03-10 15:48 UTC, HarshCasper commented
@pritamp17 

Are you still working on it?

2021-03-29 04:15 UTC, vybhav72954 commented
@pritamp17 Kindly reply by tonight, else i would be forced to close this PR for no activity.

2021-03-30 12:23 UTC, closed without merging