added maintiners in place of project admin
HarshCasper/Rotten-Scripts pull request #827
Opened 2021-03-10 15:46 UTC by haripriya9647

As this project is maintained by many folks soo projects admin is replaced by project maintainers.

Fixes #805 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] Readme Update

2021-03-10 16:22 UTC, HarshCasper requested changes

2021-03-10 16:22 UTC, HarshCasper commented on README.md
> +| <a href="https://www.linkedin.com/in/vybhav-chaturvedi-0ba82614a/"><img src="https://mpng.subpng.com/20180324/vhe/kisspng-linkedin-computer-icons-logo-social-networking-ser-facebook-5ab6ebfe5f5397.
They look stacked vertically. Can you make them look stacked horizontally for better readability?

2021-03-10 17:22 UTC, vybhav72954 requested changes
Hi there!!!

Even after your latest commit, I think they are stacked to the top to bottom

2021-03-10 17:24 UTC, vybhav72954 commented
I am pretty sure you can sort this out by using `<table>` tag

For more info, click [here](https://www.w3schools.com/html/html_tables.asp)

2021-03-11 15:05 UTC, vybhav72954 approved these changes
LGTM

2021-03-11 16:52 UTC, HarshCasper requested changes
Make an atomic commit by pushing all your commits into one single atomic commit. The overall `diff` is very small, so we don't need 5 commits for the same

2021-03-12 16:12 UTC, merged