Changed CONTRIBUTING.md
HarshCasper/Rotten-Scripts pull request #829
Opened 2021-03-10 16:18 UTC by pi-squared-4

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2021-03-10 16:48 UTC, vybhav72954 requested changes
Just a few minor changes here and there

2021-03-10 16:48 UTC, vybhav72954 commented on CONTRIBUTING.md
> +###### (This helps us save a lot of precious space.) ######
I don't think we need this line. And as a rule of thumb, we should be using the same Heading Style for every Heading used.

2021-03-10 16:48 UTC, vybhav72954 commented on CONTRIBUTING.md
> +    ## How to do that? ##
You are using an h2 after h3.

The Markdown Styling will report that as an error. Also, different types of Syntax shouldn't be used.

So either use h4 or make the line bold.

2021-03-10 16:48 UTC, vybhav72954 commented on CONTRIBUTING.md
> +    - Then link your uploaded images to readme files. An instance 👇
Can you make this `README`

2021-03-10 16:48 UTC, vybhav72954 commented on CONTRIBUTING.md
> +    - You can do that by hosting all you images and screenshots to any images hosting site such as [imgur](www.imgur.com).
Would it be possible that you add links to imgbb and postimage as well

2021-03-11 06:06 UTC, vybhav72954 requested changes

2021-03-11 06:06 UTC, vybhav72954 commented on CONTRIBUTING.md
> +    #### How to do that? ####
Hi there, all these final changes look good apart from one tiny mistake

```
H4 you have used - #### How to do that? ####
H4 that should be used - #### How to do that?
```

I don't remember their exact names, but both the style of Heading is correct, but you should follow only 1 specific method. So please change this.

2021-03-11 06:11 UTC, vybhav72954 commented
One more thing. Please Link the issue to this PR.

In the body of your Pull Request, there is a Fixes<number> string.

Kindly change the number to the Number of the Issue.

This will look like this

```
Fixes#825
```

2021-03-11 06:40 UTC, vybhav72954 approved these changes
LGTM

2021-03-11 11:41 UTC, pi-squared-4 commented
Is there something wrong left?

2021-03-11 13:50 UTC, vybhav72954 requested changes
@pi-squared-4 Hey there. There are 2 changes that you need to make.

First is the trailing hashtags in the heading.

Secondly, PLease get rid of quotes, i said that because of quotes the link is not working, so rather than adding quotes everywhere, you are supposed to remove them, I have provided an example as well.

Please try to do this in one commit only.

2021-03-11 13:50 UTC, vybhav72954 commented on CONTRIBUTING.md
> +    - You can do that by hosting all you images and screenshots to any images hosting sites such as [imgur]('https://imgur.com/'), [imgbb]('https://imgbb.com/'), [postimages]('https://postimages.org/
I asked you to get rid of quotes, not put quotes everywhere

```
[imgur](https://imgur.com/)
[imgbb](https://imgbb.com/)
```

This is what you should do.

Please get this done

2021-03-11 13:50 UTC, vybhav72954 commented on CONTRIBUTING.md
@pi-squared-4 You are yet to do this change, please note that

```
### Note : Do not add images, rather 👇 ###
```
**is wrong**.

and it should be

```
### Note : Do not add images, rather 👇
```

**This is is correct**

2021-03-11 14:47 UTC, pi-squared-4 commented
I am changing it, but I dont know how everytime, it is reverted back.

2021-03-11 15:03 UTC, vybhav72954 commented
> I am changing it, but I dont know how everytime, it is reverted back.
> I have changed it already twice.

@pi-squared-4 It worked 🥳 🥳 

Now please sort out the links and I will merge this right away.

2021-03-11 15:04 UTC, vybhav72954 commented on CONTRIBUTING.md
> +    - You can do that by hosting all you images and screenshots to any images hosting sites such as [imgur]('https://imgur.com/'), [imgbb]('https://imgbb.com/'), [postimages]('https://postimages.org/
@pi-squared-4 Just this small change

2021-03-11 15:27 UTC, vybhav72954 commented
LGTM 💯

2021-03-11 15:29 UTC, merged

2021-04-05 14:00 UTC, pi-squared-4 commented
I cannot see any points of my gssoc profile, can you help me out?

2021-04-06 06:06 UTC, vybhav72954 commented
> I cannot see any points of my gssoc profile, can you help me out?

The leaderboard is yet to be finalised