chore(pylint) : Ignore module doc string from pylint
HarshCasper/Rotten-Scripts pull request #850
Opened 2021-03-13 19:42 UTC by priyanshu20

# Description

Ignored alert from pylint about module docstring

Fixes #849 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

- [x] Documentation Update

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2021-03-13 19:44 UTC, vybhav72954 commented
@priyanshu20 While you are at this, can you add a few more codes as well. I will post the codes here.

2021-03-13 19:45 UTC, priyanshu20 commented
> @priyanshu20 While you are at this, can you add a few more codes as well. I will post the codes here.

sure

2021-03-17 11:40 UTC, vybhav72954 commented
Add these codes

```
C0103
R0914
W0702
C0411
```

2021-03-18 15:56 UTC, vybhav72954 requested changes

2021-03-18 15:56 UTC, vybhav72954 commented on .github/linters/.python-lint.yml
> +disable=F0401,W0141,W0611,W0110,W0703,W0142,C0114,C0103,R0914,W0702,C0411
Final Tags Requested:
```
E1101
C0305
R0201
R0903
W0105
W0621
W0702
W0612
W0613
```

2021-03-19 17:01 UTC, vybhav72954 commented
@HarshCasper This is good to go!

2021-03-19 17:01 UTC, vybhav72954 approved these changes

2021-03-20 08:48 UTC, merged