Added Coderforces Scraping files to Codeforces_Scraper
HarshCasper/Rotten-Scripts pull request #851
Opened 2021-03-13 20:06 UTC by iamakkkhil

# Description

This python script will let you download Problem Statements from Codeforces and save them as a pdf file. The script uses Selenium Webdriver, Pillow and fpdf library. Selenium is used with Chrome Webdriver, so having Chrome browser is a requirement.

Fixes #(291)

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2021-03-15 00:29 UTC, rahulraikwar00 commented on Python/Coderforces_Problem_Scrapper/Codeforces_problem_scrapper.py
> +
@iamakkkhil add comments to make this code more readable?

2021-03-16 05:18 UTC, HarshCasper requested changes

2021-03-16 05:18 UTC, HarshCasper commented on Python/Coderforces_Problem_Scrapper/requirements.txt
> +
Remove the line

2021-03-16 05:18 UTC, HarshCasper commented on Python/Coderforces_Problem_Scrapper/requirements.txt
> +selenium
Add package versions

2021-03-16 05:18 UTC, HarshCasper commented on Python/Coderforces_Problem_Scrapper/Codeforces_problem_scrapper.py
> +def getproblem():
Add a function docstring

2021-03-16 05:18 UTC, HarshCasper commented on Python/Coderforces_Problem_Scrapper/Codeforces_problem_scrapper.py
> +    driver = webdriver.Chrome("F:/chromedriver.exe", options=options)
Remove local references of your filepath

2021-03-16 05:18 UTC, HarshCasper commented on Python/Coderforces_Problem_Scrapper/Codeforces_problem_scrapper.py
> +os.remove('image.png')
Use a main function to drive the code

2021-03-16 05:18 UTC, HarshCasper commented on Python/Coderforces_Problem_Scrapper/README.md
> +
Remove this line

2021-03-16 06:49 UTC, iamakkkhil commented
@HarshCasper updated files accordingly.

2021-03-17 10:40 UTC, vybhav72954 requested changes
@HarshCasper The changes look good to me.

@iamakkkhil Please include some comments so that others can understand the workflow,

2021-03-17 10:40 UTC, vybhav72954 commented on Python/Coderforces_Problem_Scrapper/Codeforces_problem_scrapper.py
> +    os.remove('image.png')
Add an EOF file in the script.

2021-03-17 19:09 UTC, iamakkkhil commented
@vybhav72954 @HarshCasper Can you check this ?

2021-03-18 12:51 UTC, vybhav72954 approved these changes
@HarshCasper Good to go.

2021-03-19 16:14 UTC, HarshCasper approved these changes

2021-03-19 16:15 UTC, merged