new python README
HarshCasper/Rotten-Scripts pull request #854
Opened 2021-03-14 07:23 UTC by deepthiteki

Replaced table with Unordered list.

Fixes #796 
- [x] Documentation Update

- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2021-03-17 11:09 UTC, vybhav72954 requested changes

2021-03-17 11:09 UTC, vybhav72954 commented on Python/README.md
> +- [ASCIIfy_Image](/Python/ASCIIfy_Image)
Can we have a LOGO of python?
And a few lines about python here as well.

2021-03-17 11:09 UTC, vybhav72954 commented on Python/README.md
> +
Remove these extra lines please

2021-03-30 12:06 UTC, vybhav72954 commented
@deepthiteki Please Update

2021-03-30 12:40 UTC, HarshCasper approved these changes

2021-03-30 12:41 UTC, merged