adding network passwords
HarshCasper/Rotten-Scripts pull request #868
Opened 2021-03-18 12:02 UTC by aaadddiii

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #865 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2021-03-18 12:44 UTC, vybhav72954 requested changes
I have done a basic review.

I don't like the README at all!

It doesn't align with the template, see a few other READMEs in this Repo and make the necessary changes.

2021-03-18 12:44 UTC, vybhav72954 commented on Python/Network_passwords/script.py
> +def send_mail(email, password, message):
Missing Function Docstring

2021-03-18 12:44 UTC, vybhav72954 commented on Python/Network_passwords/script.py
> +send_mail("<Enter your gmail>", "<Enter your gmail password>", content)
Add a blank line here

2021-03-18 12:44 UTC, vybhav72954 commented on Python/Network_passwords/README.md
> +```
Add language attribute to the code fence

2021-03-18 12:44 UTC, vybhav72954 commented on Python/Network_passwords/README.md
> +open wifi-passwords.py file and give your email and password on the send_mail function before running the program on the target system
Start with a Capital Letter

2021-04-09 09:06 UTC, vybhav72954 requested changes
The README looks good.

Just one more suggestion

```
# Head 1
<Blank>
Random things
<Blank>
## Head 2 (can be any heading for that matter)
<Blank>
Random things again
```

Please insert blank lines before and after every heading (except before the top most heading)

2021-04-09 09:06 UTC, vybhav72954 commented on Python/Network_passwords/README.md
> +## packages used
Start with Capital Letter please

2021-04-09 09:06 UTC, vybhav72954 commented on Python/Network_passwords/README.md
> +![](https://i.postimg.cc/HnJhW7FJ/pic.png)
Consider adding your name as Author

2021-04-09 09:06 UTC, vybhav72954 commented on Python/Network_passwords/script.py
> +def send_mail(email, password, message):
Please add a Docstring

2021-04-09 10:33 UTC, aaadddiii commented
Necessary changes made

2021-04-09 11:05 UTC, vybhav72954 requested changes

2021-04-09 11:05 UTC, vybhav72954 commented on Python/Network_passwords/script.py
> +'''
This is not how a docstring should be.
Pls change it like this
```
def send_mail(email, password, message):
    '''
    send_mail function sends the list of passwords through given email
    '''
```

2021-04-09 11:05 UTC, vybhav72954 commented on Python/Network_passwords/script.py
> +send_mail("<Enter your gmail>", "<Enter your gmail password>", content)
Use a `.env` file here, please.
Use `decouple` module.


[This](https://github.com/HarshCasper/Rotten-Scripts/tree/master/Python/Github_Traffic) script can be used for reference.

Upload a ```.env.example``` file.

2021-04-23 03:17 UTC, aaadddiii commented
@vybhav72954 I have made changes , can you review it

2021-05-12 15:09 UTC, vybhav72954 approved these changes
Changes are apt.

2021-05-12 15:09 UTC, merged