Football club wikipedia scraper for issue #466
HarshCasper/Rotten-Scripts pull request #875
Opened 2021-03-19 15:28 UTC by RohiniRG

# Description

Script which scrapes Wikipedia to obtain Football players' club careers over the years, using Python's BeautifulSoup library.

Fixes #466 

## Type of change

_Please delete options that are not relevant._

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2021-03-19 16:59 UTC, vybhav72954 requested changes
I have requested a few minor changes

2021-03-19 16:59 UTC, vybhav72954 commented on Python/Wikipedia_Scraper/main.py
> +    returns a string suitable to concatenate in the wikipedia URL. """
There needs to be no whitespace after the triple quotes for string, alternatively what you should prefer is a white line, what I basically mean is this - 
BAD
```
    """ Takes Football player's name input from the user and
    returns a string suitable to concatenate in the wikipedia URL. """
```

GOOD

```
    """Takes Football player's name input from the user and
    returns a string suitable to concatenate in the wikipedia URL."""
```

BEST

```
"""
Takes Football player's name input from the user and
returns a string suitable to concatenate in the wikipedia URL.
"""
```

2021-03-19 16:59 UTC, vybhav72954 commented on Python/Wikipedia_Scraper/main.py
> +    """ Stores only the information regarding the club career of
Change the docstring similarly.

2021-03-19 16:59 UTC, vybhav72954 commented on Python/Wikipedia_Scraper/main.py
> +    """ To display the club career information of player collected. """
Change the docstring similarly.

2021-03-19 16:59 UTC, vybhav72954 commented on Python/Wikipedia_Scraper/main.py
> +    print()
A blank print statement?
If you want a new line use escape character.

Else consider removing it!

2021-03-19 16:59 UTC, vybhav72954 commented on Python/Wikipedia_Scraper/main.py
> +def main():
A docstring here is also recommended.

2021-03-19 16:59 UTC, vybhav72954 commented on Python/Wikipedia_Scraper/main.py
> +        print()
Blank print statement?

2021-03-19 16:59 UTC, vybhav72954 commented on Python/Wikipedia_Scraper/README.md
> +1. BeautifulSoup library:
Considering you have a `requirements.txt`

Consider using `pip3 install -r requirements.txt`

in place of bs4 and request

You can list out dependencies if you want as list though

2021-03-20 02:57 UTC, RohiniRG commented
@vybhav72954 I made the changes you mentioned, please have a look. Thank you!

2021-03-20 05:47 UTC, vybhav72954 commented
@iamakkkhil Why do i see a commit from you in the working tree?
@RohiniRG ?

2021-03-20 05:54 UTC, iamakkkhil commented
I don't know what is happening. This is the very first time we are submitting the PR. 
Can you let us know what to do now @vybhav72954 ?
Apologies for any inconvenience.

2021-03-20 08:32 UTC, RohiniRG commented
> @iamakkkhil Why do i see a commit from you in the working tree?
> @RohiniRG ?

Actually @iamakkkhil had the last merge in this repo and when I tried to push this commit, his previously merged files also got committed I guess... I am not really sure how this happened. What have I done wrong and how can I rectify this?

2021-03-20 08:34 UTC, RohiniRG commented
Sorry for this mess! I am just trying to figure out git works.

2021-03-22 12:37 UTC, HarshCasper commented
No worries @RohiniRG 

Would you be working on the same PR or make a new branch and raise a new PR? Do let us know about it. 

P.S: We want you to make mistakes because failing is sometimes a better way to learn something. Not success :)

2021-03-22 13:56 UTC, RohiniRG commented
> No worries @RohiniRG
> 
> Would you be working on the same PR or make a new branch and raise a new PR? Do let us know about it.
> 
> P.S: We want you to make mistakes because failing is sometimes a better way to learn something. Not success :)

Thank you! I would like to make a new branch and start with a new PR again.

2021-03-23 18:19 UTC, closed without merging