Added the Jupyter file for test data generator - Issue 444
HarshCasper/Rotten-Scripts pull request #879
Opened 2021-03-21 18:29 UTC by srimontidutta

Issue-444
Added the Jupyter file for test data generator of data of Students taking online courses using Faker.
#444 
Kindly check it.

2021-03-21 18:34 UTC, srimontidutta commented
Also, please change the "medium" tag on this issue to a "level" tag instead.

2021-03-22 18:10 UTC, vybhav72954 requested changes
Please Add a README file.

2021-03-23 13:29 UTC, srimontidutta commented
Added README file. Please check @vybhav72954

2021-03-27 04:05 UTC, vybhav72954 commented
Hey @srimontidutta The README you have added, is still not up tp the mark. Kindly see the Markdown part in the [guide](https://github.com/HarshCasper/Rotten-Scripts/blob/master/STYLE_GUIDELINES.md)

2021-03-27 04:10 UTC, vybhav72954 requested changes
KIndly check the [template](https://github.com/HarshCasper/Rotten-Scripts/blob/master/TEMPLATE_README.md)

Make changes accordingly

2021-03-27 04:10 UTC, vybhav72954 commented on Python/Test Data Generator/README.md
> +Student ID
Make this an ordered list

2021-03-27 04:10 UTC, vybhav72954 commented on Python/Test Data Generator/README.md
> +```python
Empty Code block?

2021-03-27 04:10 UTC, vybhav72954 commented on Python/Test Data Generator/README.md
> +The generated dataset consisting of the specified number of entries from the user is then exported to the local device in csv format.
Add CSV in code blocks as well, `csv`

2021-03-27 04:10 UTC, vybhav72954 commented on Python/Test Data Generator/README.md
> +faker.Faker() - Creates and initializes a faker generator, which can generate data by accessing properties named after the type of data we want.
Add function names in code blocks

2021-03-27 04:10 UTC, vybhav72954 commented on Python/Test Data Generator/README.md
> +### Faker
Don't use a heading rather make this part of an unordered list along with its description

2021-03-27 04:10 UTC, vybhav72954 commented on Python/Test Data Generator/README.md
> +## Library used for the generation of fake data
Rename the heading to `## Dependencies`

2021-03-27 04:10 UTC, vybhav72954 commented on Python/Test Data Generator/README.md
> +# README
Rename this heading to the name of your script

2021-03-27 04:11 UTC, vybhav72954 commented
@srimontidutta Rename the directory you made to `Test_Data_Generator`

2021-03-30 05:06 UTC, closed without merging