Script-addition  : Twitter unfollower js
HarshCasper/Rotten-Scripts pull request #940
Opened 2021-04-05 05:40 UTC by jhamadhav

# Description
Script added "Twitter_Unfollowers".
Twitter_Unfollowers is a script to track people that recently unfollowed you on Twitter.

Issue #935 is fixed in this.

## Type of change
- [ ] New feature (That is the script added)
- [ ] Documentation Update

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

## Output
![Output Pic](https://i.imgur.com/HQ68vDj.png)

2021-04-05 05:47 UTC, jhamadhav commented
@vybhav72954 please review the PR, Thank you!

2021-04-06 06:25 UTC, HarshCasper requested changes

2021-04-06 06:25 UTC, HarshCasper commented on JavaScript/Twitter_Unfollowers/.gitignore
> +apiTokens.js
We have a global `.gitignore` on the root. You can add them there :)

2021-04-06 06:25 UTC, HarshCasper commented on JavaScript/Twitter_Unfollowers/README.md
> +- Then stores it into a json file.
Keep it `JSON`

2021-04-06 06:25 UTC, HarshCasper commented on JavaScript/Twitter_Unfollowers/README.md
> +- create a file named `apiTokens.js` in the Twitter_Unfollowers folder and enter the following : ![File content](https://i.imgur.com/4UlveGE.png)
Keep it `Create`

2021-04-06 06:25 UTC, HarshCasper commented on JavaScript/Twitter_Unfollowers/README.md
> +- create a file named `apiTokens.js` in the Twitter_Unfollowers folder and enter the following : ![File content](https://i.imgur.com/4UlveGE.png)
Would it be possible to have the file inside the directory itself so that we can copy and paste our key over there :)

2021-04-06 06:25 UTC, HarshCasper commented on JavaScript/Twitter_Unfollowers/README.md
> +- cd to `Rotten-Scripts\JavaScript\Twitter_unfollowers`
Keep `cd` in backticks to highlight it

2021-04-06 06:25 UTC, HarshCasper commented on JavaScript/Twitter_Unfollowers/README.md
> +Check my [Github](https://github.jhamadhav.com) for more such projects and to connect with me check my [LinkedIn](https://linkedin.jhamadhav.com) profile.
Just add your name and hyperlink the public profile (preferrably GitHub) here. Let's keep it minimal :wink:

2021-04-06 06:25 UTC, HarshCasper commented on JavaScript/Twitter_Unfollowers/Twitter_Unfollowers.js
> +    // console.log(fromDB);
Remove these console statements

2021-04-06 06:25 UTC, HarshCasper commented on JavaScript/Twitter_Unfollowers/Twitter_Unfollowers.js
> +
Remove this line

2021-04-06 06:25 UTC, HarshCasper commented on JavaScript/Twitter_Unfollowers/twitterFunc.js
> +module.exports = { getUserId, getFollowers };
Add a new line at the EOF

2021-04-06 06:25 UTC, HarshCasper commented on JavaScript/Twitter_Unfollowers/twitterFunc.js
> +    // console.log(`Got ${users.length} users.`);
Remove these commented lines of code

2021-04-06 06:25 UTC, HarshCasper commented on JavaScript/Twitter_Unfollowers/twitterFunc.js
> +    //console.log("Retrieving followers...");
Remove this

2021-04-06 06:25 UTC, HarshCasper commented on JavaScript/Twitter_Unfollowers/dbFunc.js
> +module.exports = { read, write }
Add a new line at the EOF

2021-04-06 06:25 UTC, HarshCasper commented on JavaScript/Twitter_Unfollowers/dbFunc.js
> +        // console.log(data);
Remove this up

2021-04-06 08:10 UTC, jhamadhav commented
@HarshCasper I have made the recommended changes please check!
And thanks a lot for your thorough review 😃

2021-04-08 10:27 UTC, vybhav72954 commented
Dear @jhamadhav the correct syntax is ```Fixes #935``` (Fixes is a keyword) in your PR body. Please correct it yourself.

2021-04-08 10:29 UTC, vybhav72954 requested changes
@jhamadhav Some small changes in README, @sohamsshah Please take over from here.

2021-04-08 10:29 UTC, vybhav72954 commented on JavaScript/Twitter_Unfollowers/README.md
> +# Twitter_Unfollowers
After and before (except the first one) every heading please introduce a blank line.

2021-04-08 10:31 UTC, jhamadhav commented
@vybhav72954 is it okay now?

2021-04-08 14:48 UTC, jhamadhav commented
@vybhav72954 @sohamsshah  I have made the requested changes in the README file please check!

2021-04-12 03:36 UTC, HarshCasper approved these changes
LGTM! Thanks :tada:

2021-04-12 03:37 UTC, merged