Instagram liker Bot--- Issue 968
HarshCasper/Rotten-Scripts pull request #974
Opened 2021-04-14 14:57 UTC by sayantani11

# Description

Given an username, the bot will search for the account and auto-like all the available post of the user. It will exit by itself after all posts are liked.

Fixes #968 

## Type of change

_Please delete options that are not relevant._
- [ ] New feature (non-breaking change which adds functionality)
- [ ] 
# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My changes generate no new warnings

2021-04-14 15:00 UTC, sayantani11 commented
@HarshCasper Can you please assist me with the checks?
Like what is the error?

2021-04-14 21:45 UTC, vybhav72954 requested changes
A few changes!

2021-04-14 21:45 UTC, vybhav72954 commented on Python/Instagram-Liker-Bot/READme.md
> +# Use of Script :
Please follow the [template](https://github.com/HarshCasper/Rotten-Scripts/blob/master/TEMPLATE_README.md). The README needs a lot of alterations.

2021-04-14 21:45 UTC, vybhav72954 commented on Python/Instagram-Liker-Bot/Instagram_Liker_Bot.py
> +username.send_keys(input("Enter your username")) #enter username
Can we make a `.env` file for this input? Would be much safer and standard.

2021-04-14 21:45 UTC, vybhav72954 commented on Python/Instagram-Liker-Bot/Instagram_Liker_Bot.py
> +chrome=webdriver.Chrome(ChromeDriverManager().install())
CAn we have a more modular approach for this? Make a function and call it from a driver?

2021-04-14 21:45 UTC, vybhav72954 commented on Python/Instagram-Liker-Bot/Instagram_Liker_Bot.py
> +        break
Missing a blank line at EOF

2021-04-15 15:23 UTC, sayantani11 commented
@vybhav72954  On it....Working on the issue

2021-04-28 14:56 UTC, sohamsshah commented
@sayantani11 any updates?

2021-04-28 16:35 UTC, sayantani11 commented
@sohamsshah I was trying to use the env file and function thing..... Stuck there.... I guess I will able to do it, I am trying

2021-05-05 13:20 UTC, devRawnie commented
Hey @sayantani11, You can refer to this for an example of using env files. Be sure to add the .env file in the .gitignore file.
![env example](https://user-images.githubusercontent.com/43227329/117147255-b36dff80-add2-11eb-81fc-71889ef0f153.png)

2021-05-10 11:36 UTC, vybhav72954 commented
@sayantani11 Updates?

2021-05-13 10:52 UTC, devRawnie commented
I can work to complete this PR. Kindly assign this to me @vybhav72954

2021-05-13 11:28 UTC, vybhav72954 commented
> I can work to complete this PR. Kindly assign this to me @vybhav72954

Hey @devRawnie i understand and appreciate your willingness to contribute... But just because someone else is having some problems, doesn't mean I can pass on the work assigned to someone to somebody else entirely without taking consent. Unassigning someone just because they were unable to sort out a small thing would ultimately show my inability as a mentor. You are a frequent contributor and am pretty sure you can take any other issue.

@sayantani11 I will surely help you with the problem by tonight.

2021-05-13 12:15 UTC, devRawnie commented
I really appreciate that @vybhav72954. When I asked to be assigned this issue, that came from a place where I just wanted more points in the competition. However, I realized now that this is not just about winning in the long run 😅. More power to you sir 🙌. And I would try and help other developers in any way that I can myself.

2021-05-17 07:36 UTC, vybhav72954 requested changes

2021-05-17 07:36 UTC, vybhav72954 commented on Python/Instagram-Liker-Bot/Instagram_Liker_Bot.py
> +username.send_keys(input("Enter your username")) #enter username
Ok so look, here is what you need to do.

```
from decouple import config
```
make one .env file

It should contain your username and password.

Pass those values from the env file. The can be done using `dotenv` as well. Like [here](https://dev.to/biplov/handling-passwords-and-secret-keys-using-environment-variables-2ei0)

Finally there is a `getuser()` functionality as well just like `getpass()` can it be used?

2021-05-18 12:24 UTC, sayantani11 commented
Okay @vybhav72954 I am looking into it thanks for helping

2021-05-24 12:58 UTC, sayantani11 commented
@vybhav72954 Thank you for helping with the issue, I was doing it, but unfortunately due to a certain emergency I won't be able to continue with it.
You can assign it to @devRawnie if he wants to work on it.
Although after you helped I was able to proceed.
I am really sorry for this.

2021-05-31 08:11 UTC, HarshCasper commented
> @vybhav72954 Thank you for helping with the issue, I was doing it, but unfortunately due to a certain emergency I won't be able to continue with it.
> You can assign it to @devRawnie if he wants to work on it.
> Although after you helped I was able to proceed.
> I am really sorry for this.

No worries! You have put in a lot of hard work in this and we would love to see you succeed. You can continue working on this if you want and we won't have any problems. Let me know what you think.

2021-06-03 14:28 UTC, sayantani11 commented
@HarshCasper I would love to!!!! Thank You!!! If that's possible I would surely like to continue

2021-07-12 04:22 UTC, HarshCasper commented
> @HarshCasper I would love to!!!! Thank You!!! If that's possible I would surely like to continue

The PR would be open for the coming few weeks. Do take a look if you get time or put a comment here so that the stale bot does not close it.

2021-07-21 23:34 UTC, closed without merging