Added code to merge two pdfs using javascript
HarshCasper/Rotten-Scripts pull request #981
Opened 2021-04-15 22:47 UTC by harshita2319

# Description

Added code to merge two PDFs using Javascript.

Fixes #152 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2021-04-30 20:31 UTC, harshita2319 commented
@vybhav72954 please review!

2021-07-08 00:35 UTC, vybhav72954 approved these changes

2021-07-08 04:26 UTC, sohamsshah requested changes
Great work! @harshita2319 
Reflect to the few minor changes and it is good to merged :)

Thanks!

2021-07-08 04:26 UTC, sohamsshah commented on JavaScript/Merge_pdfs/README.md
> +
Can you describe the use-case of this particular script in more detail in the README?

2021-07-08 20:30 UTC, sohamsshah requested changes
Hi @harshita2319 , thank you for such a swift response. You have removed the underscores from the name, but haven't yet changed them to camel case.

By that I mean: 
`empty_pdf` -> `emptyPdf`
`page_pdf2` -> `pagePdf2` and so on.

Read about camelCase [here](https://www.theserverside.com/answer/Camel-case-vs-snake-case-Whats-the-difference)

Can you please make the small changes? Sorry for being a bit picky about naming but why not follow the best practices for such a good code-implementation😊💪

Again, thank you for working on this!

2021-07-08 22:29 UTC, harshita2319 commented
> Hi @harshita2319 , thank you for such a swift response. You have removed the underscores from the var and func names, but haven't yet changed them to camel case.
> 
> By that I mean they must be changed to:
> `empty_pdf` -> `emptyPdf`
> `page_pdf2` -> `pagePdf2` and so on.
> 
> Read about camelCase [here](https://www.theserverside.com/answer/Camel-case-vs-snake-case-Whats-the-difference)
> 
> Can you please make the small changes? Sorry for being a bit picky about naming but why not follow the best practices for such a good code-implementation
> 
> Again, thank you for working on this!

Ya, sorry. I've updated that. Please check. Thanks! :)

2021-07-09 04:50 UTC, sohamsshah approved these changes
Perfect LGTM! @harshita2319

2021-09-01 21:10 UTC, vybhav72954 commented
@sohamsshah I believe we are good to go with this PR right?

2021-09-02 04:33 UTC, sohamsshah commented
> @sohamsshah I believe we are good to go with this PR right?

Yes

2021-09-02 19:04 UTC, merged